### ISSUE TITLE
GriefPrevention - B4F 137 - Accessing a Chest claimed by another player is possible, same with editing land in a claim

### ISSUE THREAD

**Issue by L0rdLogan** [CardboardPowered/cardboard#104]
[15:05:37] [Server thread/FATAL]: Could not pass event BlockBreakEvent to GriefPrevention v16.16.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Bukkit4Fabric-1.16.4%20(3).jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Bukkit4Fabric-1.16.4%20(3).jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Bukkit4Fabric-1.16.4%20(3).jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Bukkit4Fabric-1.16.4%20(3).jar:?]
        at net.minecraft.class_3225.handler$zzi000$blockBreak(class_3225.java:742) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14266(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_21717(class_3225.java:222) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.handler$zzi000$processBlockBreakingActionBF(class_3225.java:699) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:1008) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:40) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at java.lang.String.replace(Unknown Source) ~[?:1.8.0_251]
        at me.ryanhamshire.GriefPrevention.DataStore.getMessage(DataStore.java:1795) ~[?:?]
        at me.ryanhamshire.GriefPrevention.Claim.allowContainers(Claim.java:574) ~[?:?]
        at me.ryanhamshire.GriefPrevention.Claim.allowBuild(Claim.java:410) ~[?:?]
        at me.ryanhamshire.GriefPrevention.Claim.allowBreak(Claim.java:492) ~[?:?]
        at me.ryanhamshire.GriefPrevention.GriefPrevention.allowBreak(GriefPrevention.java:3478) ~[?:?]
        at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockBreak(BlockEventHandler.java:115) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[Bukkit4Fabric-1.16.4%20(3).jar:?]
        ... 25 more

**Comment by gatewaytofredom** [comment]
`[Server thread/FATAL]: Could not pass event PlayerInteractEvent to GriefPrevention v16.16.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Bukkit4Fabric-1.16.4.jar:?]
        at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:248) ~[Bukkit4Fabr
ic-1.16.4.jar:?]
        at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:215) ~[Bukkit4Fabr
ic-1.16.4.jar:?]
        at net.minecraft.class_3225.handler$zzg000$processBlockBreakingActionBF(class_3225.java:612) ~[intermediary-server.jar:?
]
        at net.minecraft.class_3225.method_14263(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:1008) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:40) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ArrayIndexOutOfBoundsException`

I'm not sure what this affects, because the plugin seems to be working fine regardless of what this error is from.
