### ISSUE TITLE
Placing a modded items in the world - AE2

### ISSUE THREAD

**Issue by L0rdLogan** [CardboardPowered/cardboard#106]
Error in console: 

[21:32:12] [Server thread/INFO]: [STDOUT]: isOnline: com.mojang.authlib.GameProfile@7516814d[id=de265a7c-89ba-4a81-8e34-cd636186287f,name=<null>,properties={},legacy=false], false
[21:32:19] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
        at net.minecraft.class_1747.handler$zzf000$place1(class_1747.java:587) ~[intermediary-server.jar:?]
        at net.minecraft.class_1747.method_7712(class_1747.java) ~[intermediary-server.jar:?]
        at appeng.block.AEBaseBlockItem.method_7712(AEBaseBlockItem.java:125) ~[appliedenergistics2-fabric-8.1.0-alpha.12%20(1).jar:?]
        at appeng.parts.PartPlacement.place(PartPlacement.java:184) ~[appliedenergistics2-fabric-8.1.0-alpha.12%20(1).jar:?]
        at appeng.core.api.ApiPart.placeBus(ApiPart.java:39) ~[appliedenergistics2-fabric-8.1.0-alpha.12%20(1).jar:?]
        at appeng.items.parts.PartItem.method_7884(PartItem.java:50) ~[appliedenergistics2-fabric-8.1.0-alpha.12%20(1).jar:?]
        at net.minecraft.class_1799.method_7981(class_1799.java:1213) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.handler$zzi000$interactBlock(class_3225.java:847) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

Screenshot with B4F build 139: Item is non-existent and can be walked through
![2020-12-20_21 33 26](https://user-images.githubusercontent.com/5092548/102725023-acef5780-430b-11eb-944a-87e545b77de5.png)

Screenshot without B4F: Item existent 
![2020-12-20_21 37 28](https://user-images.githubusercontent.com/5092548/102725044-cee8da00-430b-11eb-8ad6-836b4ea4645c.png)

**Comment by IsaiahPatton** [comment]
does this still exist in latest update?

**Comment by L0rdLogan** [comment]
> does this still exist in latest update?

I'll check

**Comment by L0rdLogan** [comment]
Interesting update: Since build 150 when I attempt to place those clocks - it now comes up with the following error:

[15:14:54] [Server thread/FATAL]: Could not pass event PlayerInteractEvent to WorldGuard v7.0.4+f7ff984
java.lang.ArrayIndexOutOfBoundsException: 2067
        at com.sk89q.worldguard.bukkit.util.Materials.isSpawnEgg(Materials.java:1059) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.handleBlockRightClick(EventAbstractionListener.java:1152) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteract(EventAbstractionListener.java:480) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor217.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[CardboardMod-1.16.4%20(2).jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[CardboardMod-1.16.4%20(2).jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[CardboardMod-1.16.4%20(2).jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[CardboardMod-1.16.4%20(2).jar:?]
        at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:254) ~[CardboardMod-1.16.4%20(2).jar:?]
        at net.minecraft.class_3225.handler$zfi001$interactBlock(class_3225.java:802) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[15:14:54] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
        at net.minecraft.class_1747.handler$zff000$place1(class_1747.java:586) ~[intermediary-server.jar:?]
        at net.minecraft.class_1747.method_7712(class_1747.java) ~[intermediary-server.jar:?]
        at appeng.block.AEBaseBlockItem.method_7712(AEBaseBlockItem.java:125) ~[appliedenergistics2-fabric-8.1.0-alpha.13.jar:?]
        at appeng.parts.PartPlacement.place(PartPlacement.java:184) ~[appliedenergistics2-fabric-8.1.0-alpha.13.jar:?]
        at appeng.core.api.ApiPart.placeBus(ApiPart.java:39) ~[appliedenergistics2-fabric-8.1.0-alpha.13.jar:?]
        at appeng.items.parts.PartItem.method_7884(PartItem.java:50) ~[appliedenergistics2-fabric-8.1.0-alpha.13.jar:?]
        at net.minecraft.class_1799.method_7981(class_1799.java:1213) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.handler$zfi001$interactBlock(class_3225.java:847) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by IsaiahPatton** [comment]
placing modded items should be fixed now
