### ISSUE TITLE
Crash when loading on the client (Integrated Server)

### ISSUE THREAD

**Issue by choalover** [CardboardPowered/cardboard#110]
It crashes before it can generate the world if I install this mod and I even tried with only Fabric Loader installed to see if it would fix the issue.

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/23/20 1:46 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:1968)
	at net.minecraft.class_1132.method_3823(class_1132.java:67)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5390641768 bytes (5140 MB) / 6543114240 bytes (6240 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Player Count: 0 / 8; []
	Data Packs: vanilla
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by IsaiahPatton** [comment]
Client currently not supported.
