### ISSUE TITLE
EssentialsX Error

### ISSUE THREAD

**Issue by X00LA** [CardboardPowered/cardboard#117]
Hi,
I installed Cardboard and EssentialsX on my server. When I startup I get the following error in console

[12:07:13] [Server thread/INFO]: [Essentials] You are running a server with limited API functionality. EssentialsX will still work, but certain features may be disabled.
[12:07:14] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException
[12:07:14] [Server thread/INFO]: [STDERR]:      at net.ess3.nms.refl.providers.ReflServerStateProvider.<init>(ReflServerStateProvider.java:20)
[12:07:14] [Server thread/INFO]: [STDERR]:      at com.earth2me.essentials.Essentials.onEnable(Essentials.java:309)
[12:07:14] [Server thread/INFO]: [STDERR]:      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:07:14] [Server thread/INFO]: [STDERR]:      at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[12:07:14] [Server thread/INFO]: [STDERR]:      at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[12:07:14] [Server thread/INFO]: [STDERR]:      at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:456)
[12:07:14] [Server thread/INFO]: [STDERR]:      at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:387)
[12:07:14] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:2040)
[12:07:14] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3176.method_3823(class_3176.java:179)
[12:07:14] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
[12:07:14] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[12:07:14] [Server thread/INFO]: [STDERR]:      at java.lang.Thread.run(Unknown Source)

It would be nice if you could fix it.

Thank you

**Comment by L0rdLogan** [comment]
Will be fixed (hopefully) when the API is fully implamented!

**Comment by X00LA** [comment]
Thank you.

**Comment by IsaiahPatton** [comment]
Move to Paper API fixed error (as PaperLib is detected instead of reflection)
