### ISSUE TITLE
bukkit.entity.Villager.Profession.TECHNICIAN crashing a server 

### ISSUE THREAD

**Issue by EnvyEnfys** [CardboardPowered/cardboard#118]
java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.Villager.Profession.TECHNICIAN
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.bukkit.entity.Villager$Profession.valueOf(Villager.java:1)
	at org.cardboardpowered.impl.entity.VillagerImpl.nmsToBukkitProfession(VillagerImpl.java:107)
	at net.minecraft.class_4114.md982960$lambda$run$3$0(class_4114.java:1042)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_4114.method_18988(class_4114.java:1040)
	at net.minecraft.class_4114.method_18920(class_4114.java:23)
	at net.minecraft.class_4097.method_18922(class_4097.java:49)
	at net.minecraft.class_4095.method_18891(class_4095.java:506)
	at net.minecraft.class_4095.method_19542(class_4095.java:465)
	at net.minecraft.class_1646.method_5958(class_1646.java:272)
	at net.minecraft.class_1308.method_6023(class_1308.java:744)
	at net.minecraft.class_1309.method_6007(class_1309.java:2508)
	at net.minecraft.class_1308.method_6007(class_1308.java:542)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_1646.method_5773(class_1646.java:313)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.bukkit.entity.Villager$Profession.valueOf(Villager.java:1)
	at org.cardboardpowered.impl.entity.VillagerImpl.nmsToBukkitProfession(VillagerImpl.java:107)
	at net.minecraft.class_4114.md982960$lambda$run$3$0(class_4114.java:1042)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_4114.method_18988(class_4114.java:1040)
	at net.minecraft.class_4114.method_18920(class_4114.java:23)
	at net.minecraft.class_4097.method_18922(class_4097.java:49)
	at net.minecraft.class_4095.method_18891(class_4095.java:506)
	at net.minecraft.class_4095.method_19542(class_4095.java:465)
	at net.minecraft.class_1646.method_5958(class_1646.java:272)
	at net.minecraft.class_1308.method_6023(class_1308.java:744)
	at net.minecraft.class_1309.method_6007(class_1309.java:2508)
	at net.minecraft.class_1308.method_6007(class_1308.java:542)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_1646.method_5773(class_1646.java:313)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: minecraft:villager (net.minecraft.class_1646)
	Entity ID: 3215
	Entity Name: Villager
	Entity's Exact location: -406.75, 65.00, 333.78
	Entity's Block location: World: (-407,65,333), Chunk: (at 9,4,13 in -26,20; contains blocks -416,0,320 to -401,255,335), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.05, -0.08, 0.05
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

**Comment by PixelatedBruh** [comment]
I think the technician is from the phonos mod

**Comment by ghost** [comment]
simple hack
```
diff --git a/src/main/java/org/cardboardpowered/impl/entity/VillagerImpl.java b/src/main/java/org/cardboardpowered/impl/entity/VillagerImpl.java
index 0fcdaa3..eb1aa5b 100644
--- a/src/main/java/org/cardboardpowered/impl/entity/VillagerImpl.java
+++ b/src/main/java/org/cardboardpowered/impl/entity/VillagerImpl.java
@@ -107,7 +107,11 @@ public class VillagerImpl extends AbstractVillagerImpl implements Villager {
     }
 
     public static Profession nmsToBukkitProfession(VillagerProfession nms) {
-        return Profession.valueOf(Registry.VILLAGER_PROFESSION.getId(nms).getPath().toUpperCase(Locale.ROOT));
+        try {
+            return Profession.valueOf(Registry.VILLAGER_PROFESSION.getId(nms).getPath().toUpperCase(Locale.ROOT));
+        } catch (Exception e) {
+            return Profession.valueOf(Registry.VILLAGER_PROFESSION.getId(VillagerProfession.NONE).getPath().toUpperCase(Locale.ROOT));
+        }
     }
 
     public static VillagerProfession bukkitToNmsProfession(Profession bukkit) {
@@ -157,4 +161,4 @@ public class VillagerImpl extends AbstractVillagerImpl implements Villager {
         // TODO Auto-generated method stub
     }
 
-}
\ No newline at end of file
+}
```

**Comment by 27rogi** [comment]
Actual problem with last version on 1.18.1
