### ISSUE TITLE
NoSuchFile Exception with Build 141

### ISSUE THREAD

**Issue by UnbreakCode** [CardboardPowered/cardboard#123]
updated the build on my server and the server won't boot up anymore.

log:

[00:55:40] [Server thread/INFO]: JavaC Debug: code too large
[00:55:40] [Server thread/INFO]: JavaC Debug: lib\Material.java uses or overrides a deprecated API.
[00:55:40] [Server thread/INFO]: JavaC Debug: lib\Material.java uses unchecked or unsafe operations.
[00:55:40] [Server thread/INFO]: [STDERR]: java.nio.file.NoSuchFileException: lib\Material.class
[00:55:40] [Server thread/INFO]: [STDERR]: 	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at java.nio.file.Files.newByteChannel(Unknown Source)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at java.nio.file.Files.newByteChannel(Unknown Source)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at java.nio.file.Files.readAllBytes(Unknown Source)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at com.javazilla.bukkitfabric.MakeMaterial.make(MakeMaterial.java:70)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3176.handler$zzd000$init(class_3176.java:722)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3176.method_3823(class_3176.java:155)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[00:55:40] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[00:55:40] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/bukkit/Material
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
	at org.bukkit.craftbukkit.util.CraftMagicNumbers.<clinit>(CraftMagicNumbers.java:84) ~[Bukkit4Fabric-1.16.4.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.handler$zzd000$init(MinecraftDedicatedServer:727) ~[?:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.setupServer(MinecraftDedicatedServer:155) ~[?:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:645) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Material
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	... 6 more
[00:55:40] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: null
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
	at net.minecraft.server.MinecraftServer.save(MinecraftServer:572) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.shutdown(MinecraftServer:599) ~[intermediary-server.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.shutdown(MinecraftDedicatedServer:567) ~[?:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:707) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[00:55:40] [Server thread/INFO]: Goodbye!

**Comment by IsaiahPatton** [comment]
`[00:55:40] [Server thread/INFO]: JavaC Debug: code too large`
Oh no, I didn't know that JC had a limit.

**Comment by UnbreakCode** [comment]
[Material.zip](https://github.com/CardboardPowered/cardboard/files/5757454/Material.zip)

**Comment by IsaiahPatton** [comment]
Should now be fixed in the latest update
https://github.com/CardboardPowered/cardboard/commit/719f9e4ab1ecaf78c78d1304372f48c21b8950fa
