### ISSUE TITLE
Inventory not opening in inventories in Agape Space Mod - Oxide Power Generator

### ISSUE THREAD

**Issue by L0rdLogan** [CardboardPowered/cardboard#124]
[12:23:45] [Server thread/FATAL]: Error executing task on Server
java.lang.RuntimeException: Cannot load class agap.main.AgapeModClient in environment type SERVER
        at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:75) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:152) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at agap.main.PowerGen$PowerGenBlockEntity.createMenu(PowerGen.java:227) ~[agape_space-0.0.3.jar:?]
        at net.minecraft.class_3222.handler$zfk000$openHandledScreen(class_3222.java:1785) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_17355(class_3222.java) ~[intermediary-server.jar:?]
        at agap.main.PowerGen.method_9534(PowerGen.java:97) ~[agape_space-0.0.3.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:894) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.handler$zek001$interactBlock(class_3225.java:830) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by L0rdLogan** [comment]
Not a B4F issue, sorry - really need to start validating these before reporting
