### ISSUE TITLE
EssentialsZ

### ISSUE THREAD

**Issue by L0rdLogan** [CardboardPowered/cardboard#130]
Spamming console - B4F build 142 - issue mentioned doesn't seem to be in the TODO lists

[17:51:01] [Server thread/WARN]: [EssentialsZ] Task #28 for EssentialsZ v1.3.0generated an exception
java.lang.NullPointerException: null
        at me.darkwinged.Essentials.REWORK.Events.World.Tablist$1.run(Tablist.java:29) ~[?:?]
        at com.javazilla.bukkitfabric.impl.scheduler.BukkitTaskImpl.run(BukkitTaskImpl.java:74) ~[Bukkit4Fabric-1.16.4%20(8).jar:?]
        at com.javazilla.bukkitfabric.impl.scheduler.BukkitSchedulerImpl.mainThreadHeartbeat(BukkitSchedulerImpl.java:357) ~[Bukkit4Fabric-1.16.4%20(8).jar:?]
        at net.minecraft.server.MinecraftServer.handler$zeg000$doBukkitRunnables(MinecraftServer.java:3657) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

Plugin link: https://www.spigotmc.org/resources/essentialsz.86617/

**Comment by L0rdLogan** [comment]
Creating warps yields:

[18:04:50] [Server thread/INFO]: L0rdLogan issued server command: /warps
Jan 03, 2021 6:04:50 PM net.minecraft.class_3244 handler$zgk000$executeCommand
SEVERE: null
org.bukkit.command.CommandException: Unhandled exception executing command 'warps' in plugin EssentialsZ v1.3.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:870)
        at net.minecraft.class_3244.handler$zgk000$executeCommand(class_3244.java:1779)
        at net.minecraft.class_3244.method_14370(class_3244.java)
        at net.minecraft.class_3244.method_31286(class_3244.java:1876)
        at net.minecraft.class_3244.method_12048(class_3244.java:1177)
        at net.minecraft.class_2797.method_12115(class_2797.java:36)
        at net.minecraft.class_2797.method_11054(class_2797.java:9)
        at net.minecraft.class_2600.method_11072(class_2600.java:21)
        at net.minecraft.class_3738.run(class_3738.java:18)
        at net.minecraft.class_1255.method_18859(class_1255.java:144)
        at net.minecraft.class_4093.method_18859(class_4093.java:23)
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761)
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155)
        at net.minecraft.class_1255.method_16075(class_1255.java:118)
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743)
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737)
        at net.minecraft.class_1255.method_18857(class_1255.java:127)
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at me.darkwinged.Essentials.REWORK.Commands.Teleport.cmd_Warps.onCommand(cmd_Warps.java:29)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
        ... 22 more
