### ISSUE TITLE
Server will not launch when starting with JAVA 11 runtime

### ISSUE THREAD

**Issue by DWVoid** [CardboardPowered/cardboard#136]
It seems the javac-1.8.0-u20 really does not want to start under java 11. The compiler crashed with the following exception:
```
java.lang.NullPointerException
        at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:149)
        at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:134)
        at com.sun.tools.javac.file.Locations.access$000(Locations.java:71)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.computePath(Locations.java:617)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.lazy(Locations.java:643)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.getLocation(Locations.java:577)
        at com.sun.tools.javac.file.Locations.getLocation(Locations.java:678)
        at com.sun.tools.javac.file.JavacFileManager.getLocation(JavacFileManager.java:803)
        at com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:617)
        at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2747)
        at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2444)
        at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
        at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
        at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
        at com.sun.tools.javac.comp.Enter.visitTopLevel(Enter.java:300)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
        at com.sun.tools.javac.comp.Enter.classEnter(Enter.java:258)
        at com.sun.tools.javac.comp.Enter.classEnter(Enter.java:272)
        at com.sun.tools.javac.comp.Enter.complete(Enter.java:486)
        at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
        at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:855)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at com.javazilla.bukkitfabric.MakeMaterial.compile(MakeMaterial.java:185)
        at com.javazilla.bukkitfabric.MakeMaterial.make(MakeMaterial.java:71)
        at net.minecraft.class_3176.handler$zzb000$init(class_3176.java:721)
        at net.minecraft.class_3176.method_3823(class_3176.java:155)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
This seems to be a well known problem after a quick search on the internet. I was able to trick the process to proceed beyond this  by replacing the compiler with a newer 1.9 version but it also immediately stopped with a report of having version 55 instead of 53 of the binary code of some JDK module, which is to expected since JDK11 has version 55 binary.

Also, it seems that google/error-prone lint has dropped the javac project beyond java 9. I would perfectly accept the server to require a full jdk installation based on JAVA_HOME as I think this is pretty much how every java11 server is installed.

I will try do dig this a little deeper myself after this.

**Comment by DWVoid** [comment]
After checking the latest code it seems that this is already fixed. 
However, it would be nice to change the version limit. Oracle Java 8, 9, 10 appears to still release pre-build JREs, which some of the server operators might be using.
Please close after reading this. Thanks
