### ISSUE TITLE
Modded chests/backpacks inventorys dont open (v148)

### ISSUE THREAD

**Issue by RawrMaoster** [CardboardPowered/cardboard#137]
In any mod with chests the inventory wont open. 

Packed for example. (and others iv trested) Display this message in console:

[00:25:30] [Server thread/INFO]: Using generic InventoryView for ScreenHandler (inventory provided by a mod?

**Comment by RawrMaoster** [comment]
**Just an update from testing.

Chest mods that dont open:**
packed-mc1.16.3-1.0.8: https://www.curseforge.com/minecraft/mc-mods/packed-storage/files/all
expandedstorage-5.6.31+1.16.4: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/all

**Backpack mods that dont open:**
inmis-1.3.1-1.16.2: https://www.curseforge.com/minecraft/mc-mods/inmis/files/all

**For some reason who it has no issues with** simplebackpacks: https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric/files/all

**Comment by L0rdLogan** [comment]
> **Just an update from testing.**
> 
> **Chest mods that dont open:**
> packed-mc1.16.3-1.0.8: https://www.curseforge.com/minecraft/mc-mods/packed-storage/files/all
> expandedstorage-5.6.31+1.16.4: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/all
> 
> **Backpack mods that dont open:**
> inmis-1.3.1-1.16.2: https://www.curseforge.com/minecraft/mc-mods/inmis/files/all
> 
> **For some reason who it has no issues with** simplebackpacks: https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric/files/all

I think it's because SimpleBackpacks doesn't use a modded GUI, but the vanilla one

**Comment by RawrMaoster** [comment]
> I think it's because SimpleBackpacks doesn't use a modded GUI, but the vanilla one

I had a similar thought because a sakura mod that has a chests acts like a vanilla chest and works.

**Comment by IsaiahPatton** [comment]
latest update improved on modded inventories. This might be fixed but I haven't done testing yet.

**Comment by choalover** [comment]
This issue still occurs in the latest version.

**Comment by L0rdLogan** [comment]
Build 150:

[16:44:07] [Server thread/INFO]: Using generic InventoryView for ScreenHandler (inventory provided by a mod?)

**Comment by skerit** [comment]
I'm having a similar issue with `DeepStoragePlus` plugin

**Comment by MoreFoxBeans** [comment]
I'm having the same issue with the Inmis mod. Is there still not a fix?

**Comment by unilock** [comment]
Still happening on release `#50.1`, tested with [Inmis'](https://www.curseforge.com/minecraft/mc-mods/inmis) backpacks.

```
[06:31:36] [Netty Epoll Server IO #6/ERROR]: Encountered exception while handling in channel with name "inmis:open_backpack"
java.lang.IllegalStateException: InventoryOpenEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:612) ~[paper-api-1.17-dev.jar:?]
	at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callInventoryOpenEvent(BukkitEventFactory.java:349) ~[Cardboard-1.17-1.18.jar:?]
	at net.minecraft.class_3222.handler$bhc000$openHandledScreen_c(class_3222.java:2913) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_17355(class_3222.java) ~[server-intermediary.jar:?]
	at draylar.inmis.item.BackpackItem.openScreen(BackpackItem.java:58) ~[inmis-2.5.1-1.18.1.jar:?]
	at draylar.inmis.network.ServerNetworking.receiveOpenBackpackPacket(ServerNetworking.java:45) ~[inmis-2.5.1-1.18.1.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:89) ~[fabric-networking-api-v1-1.0.19+d7c144a865-dce01c891e65d5dc.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:38) ~[fabric-networking-api-v1-1.0.19+d7c144a865-dce01c891e65d5dc.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) [fabric-networking-api-v1-1.0.19+d7c144a865-dce01c891e65d5dc.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) [fabric-networking-api-v1-1.0.19+d7c144a865-dce01c891e65d5dc.jar:?]
	at net.minecraft.class_3244.handler$cgb000$handleCustomPayloadReceivedAsync(class_3244.java:3917) [server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) [server-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) [server-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) [server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:163) [server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:150) [server-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:53) [server-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[06:31:36] [Server thread/INFO]: PLAYER lost connection: Internal Exception: java.lang.IllegalStateException: InventoryOpenEvent may only be triggered synchronously.
```

It's a shame, really, because I can't find any Fabric mod that implements `/home` / `/spawn` / `/tpa` "correctly"...
