### ISSUE TITLE
Geyser-Fabric mod seems to break some Plugins loading

### ISSUE THREAD

**Issue by L0rdLogan** [CardboardPowered/cardboard#139]
Error: 

[18:11:26] [Server thread/FATAL]: Could not load 'plugins\LuckPerms-Bukkit-5.2.78.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/bukkit/craftbukkit/util/Commodore.convert([BZLjava/lang/String;)[B @34: invokevirtual
  Reason:
    Type 'org/objectweb/asm/tree/ClassNode' (current frame, stack[1]) is not assignable to 'org/objectweb/asm/ClassVisitor'
  Current Frame:
    bci: @34
    flags: { }
    locals: { '[B', integer, 'java/lang/String', 'org/objectweb/asm/tree/ClassNode', 'org/objectweb/asm/ClassReader', 'org/objectweb/asm/ClassWriter' }
    stack: { 'org/objectweb/asm/ClassReader', 'org/objectweb/asm/tree/ClassNode', integer }
  Bytecode:
    0x0000000: bb00 1e59 b700 1f4e bb00 2159 2ab7 0024
    0x0000010: 3a04 bb00 2659 1904 03b7 0029 3a05 1904
    0x0000020: 2d07 b600 2db2 0033 2db6 0037 5719 04bb
    0x0000030: 0007 5912 3819 052c 1bb7 003b 03b6 002d
    0x0000040: 1905 b600 3fb0

        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[CardboardMod-1.16.4%20-%20148.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[CardboardMod-1.16.4%20-%20148.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[CardboardMod-1.16.4%20-%20148.jar:?]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:368) ~[CardboardMod-1.16.4%20-%20148.jar:?]
        at net.minecraft.class_3176.handler$zzk000$init(class_3176.java:741) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/bukkit/craftbukkit/util/Commodore.convert([BZLjava/lang/String;)[B @34: invokevirtual
  Reason:
    Type 'org/objectweb/asm/tree/ClassNode' (current frame, stack[1]) is not assignable to 'org/objectweb/asm/ClassVisitor'
  Current Frame:
    bci: @34
    flags: { }
    locals: { '[B', integer, 'java/lang/String', 'org/objectweb/asm/tree/ClassNode', 'org/objectweb/asm/ClassReader', 'org/objectweb/asm/ClassWriter' }
    stack: { 'org/objectweb/asm/ClassReader', 'org/objectweb/asm/tree/ClassNode', integer }
  Bytecode:
    0x0000000: bb00 1e59 b700 1f4e bb00 2159 2ab7 0024
    0x0000010: 3a04 bb00 2659 1904 03b7 0029 3a05 1904
    0x0000020: 2d07 b600 2db2 0033 2db6 0037 5719 04bb
    0x0000030: 0007 5912 3819 052c 1bb7 003b 03b6 002d
    0x0000040: 1905 b600 3fb0

        at org.bukkit.craftbukkit.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:396) ~[CardboardMod-1.16.4%20-%20148.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[CardboardMod-1.16.4%20-%20148.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[CardboardMod-1.16.4%20-%20148.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[CardboardMod-1.16.4%20-%20148.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[CardboardMod-1.16.4%20-%20148.jar:?]
        ... 8 more

**Comment by IsaiahPatton** [comment]
Issue is with Geyser. They include a separate version of ASM in the mod _(why does Fabric even allow this?)_
Any other mod that makes use of ASM will also fail.

![image](https://user-images.githubusercontent.com/16439221/104659781-47d11c80-5693-11eb-8d81-65a59a721983.png)

**Comment by rtm516** [comment]
Geyser-Fabric was the first fabric mod someone in our team had worked on so its likely got a few issues. A PR to fix these would be appreciated. @Camotoy will likely expand upon this as he did most of the work on our Fabric mod.
https://github.com/GeyserMC/Geyser-Fabric

**Comment by Camotoy** [comment]
Yeah, that's my first foray into both Gradle and Fabric! I'll try to take a stab at fixing this, though.

**Comment by IsaiahPatton** [comment]
Incase it may be helpful, here's how I fixed Cardboard including ASM:
https://github.com/CardboardPowered/cardboard/blob/master/build.gradle#L100

**Comment by Camotoy** [comment]
Thanks for the link! Ideally this is fixed with https://github.com/GeyserMC/Geyser-Fabric/commit/1bcbf3fe2f21473930b676e8c17f560939d64990.

**Comment by IsaiahPatton** [comment]
Unfortunately ASM seems to still be there.
Relocation works although. 
```
    relocate("org.objectweb.asm", "org.geysermc.relocate.asm")
    relocate("org.yaml", "org.geysermc.relocate.yaml")
```

**Comment by Camotoy** [comment]
Yeah, I've been working on that. Any form of exclusion isn't working, but the relocating definitely does. I'll push a build that does that now, but since I assume the dependency is unneeded in Fabric, I'd like to remove it entirely.

Is that other dependency also highly recommended to be relocated?

**Comment by IsaiahPatton** [comment]
I don't think YAML needs to be relocated, I just included it as an example.

**Comment by Camotoy** [comment]
This *should* be fixed.
