### ISSUE TITLE
Trouble with Lithium Mod

### ISSUE THREAD

**Issue by bingling-sama** [CardboardPowered/cardboard#143]
I try to use Lithium and Cardboard in a fabric server (version: 1.16.4).
It seems that Cardboard has a mixin trouble.
Here is the log.
```
[23:08:46] [main/INFO]: Loading for game Minecraft 1.16.4
[23:08:47] [main/INFO]: [FabricLoader] Loading 50 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.1, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, lithium@0.6.1, fabric-dimensions-v1@2.0.2+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.29.4+1.16, carpet@1.4.24, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.4, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, fabric-command-api-v1@1.0.10+ca58154a7d, phosphor@0.7.0+build.10, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, cardboard@149, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, krypton@0.1.1, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[23:08:47] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/FabricServer/server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[23:08:51] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[23:08:53] [main/FATAL]: Mixin apply failed lithium.mixins.json:world.block_entity_ticking.WorldMixin -> net.minecraft.class_1937: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method method_8426 in lithium.mixins.json:world.block_entity_ticking.WorldMixin cannot reduce visibiliy of PUBLIC target method
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method method_8426 in lithium.mixins.json:world.block_entity_ticking.WorldMixin cannot reduce visibiliy of PUBLIC target method
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:466) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:439) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:403) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:333) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.class_2246.<clinit>(class_2246.java:99) ~[intermediary-server.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[intermediary-server.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[intermediary-server.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[intermediary-server.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[intermediary-server.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) [?:1.8.0_271]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-server.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) [intermediary-server.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-server.jar:?]
	at net.minecraft.server.Main.main(Main.java:87) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]

```

**Comment by IsaiahPatton** [comment]
Does this happen with just Lithium and no other mods?

**Comment by bingling-sama** [comment]
I tested all mods one by one just now.
It crashed with just Lithium & fabric-api.
And it also crashed with just Krypton & fabric-api.
Here is the log which it crashed with Krypton.
```
[21:36:08] [main/INFO]: Loading for game Minecraft 1.16.4
[21:36:08] [main/INFO]: [FabricLoader] Loading 47 mods: fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.4, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabric-command-api-v1@1.0.10+ca58154a7d, fabricloader@0.11.1, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, lithium@0.6.1, fabric-dimensions-v1@2.0.2+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, java@8, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, cardboard@149, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.29.4+1.16, fabric-models-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[21:36:09] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/FabricServer/server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[21:36:13] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[21:36:15] [main/FATAL]: Mixin apply failed lithium.mixins.json:world.block_entity_ticking.WorldMixin -> net.minecraft.class_1937: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method method_8426 in lithium.mixins.json:world.block_entity_ticking.WorldMixin cannot reduce visibiliy of PUBLIC target method
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method method_8426 in lithium.mixins.json:world.block_entity_ticking.WorldMixin cannot reduce visibiliy of PUBLIC target method
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:466) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:439) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:403) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:333) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.class_2246.<clinit>(class_2246.java:99) ~[intermediary-server.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[intermediary-server.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[intermediary-server.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[intermediary-server.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[intermediary-server.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) [?:1.8.0_271]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-server.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) [intermediary-server.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-server.jar:?]
	at net.minecraft.server.Main.main(Main.java:87) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]

```

**Comment by IsaiahPatton** [comment]
Should be fixed in latest update now
