### ISSUE TITLE
Can not running on openj9

### ISSUE THREAD

**Issue by 1a2s3d4f1** [CardboardPowered/cardboard#144]
Minecraft 1.16.4
MOD:CardboardMod-1.16.4 and other mod

https://github.com/eclipse/openj9/issues/11671
If use openj9 to launch server ,The server will crash.
```
[00:33:26] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:147) ~[?:1.8.0
_272]
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.jav
a:136) ~[?:1.8.0_272]
        at org.bukkit.craftbukkit.util.CraftMagicNumbers.test(CraftMagicNumbers.
java:183) ~[CardboardMod-1.16.4.jar:?]
        at com.javazilla.bukkitfabric.MakeMaterial.make(MakeMaterial.java:97) ~[
CardboardMod-1.16.4.jar:?]
        at net.minecraft.class_3176.handler$zzh000$init(class_3176.java:721) ~[i
ntermediary-server.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:155) ~[intermedi
ary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.jav
a:645) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.jav
a:257) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer$$Lambda$3434/000000000000000000.
run(Unknown Source) [intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]
Caused by: java.lang.IllegalStateException: java.lang.NoSuchFieldException: enum
ConstantDirectory
        at io.izzel.arclight.api.EnumHelper.<clinit>(EnumHelper.java:95) ~[Cardb
oardMod-1.16.4.jar:?]
        ... 8 more
Caused by: java.lang.NoSuchFieldException: enumConstantDirectory
        at java.lang.Class.getDeclaredField(Class.java:825) ~[?:1.8.0_272]
        at io.izzel.arclight.api.EnumHelper.<clinit>(EnumHelper.java:90) ~[Cardb
oardMod-1.16.4.jar:?]
        ... 8 more
```
[crash-2021-01-23_12.45.30-server.zip](https://github.com/CardboardPowered/cardboard/files/5892776/crash-2021-01-23_12.45.30-server.zip)

**Comment by 1a2s3d4f1** [comment]
enumVars
