### ISSUE TITLE
No other mod, but server crashed

### ISSUE THREAD

**Issue by ICEgold777** [CardboardPowered/cardboard#148]
**Thank you for making this mod, but I encountered some problems in the process of using **

Time: 21-2-2 下午8:44
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/bukkit/Material
	at org.bukkit.craftbukkit.util.CraftMagicNumbers.<clinit>(CraftMagicNumbers.java:94)
	at net.minecraft.class_3176.handler$zzb000$init(class_3176.java:726)
	at net.minecraft.class_3176.method_3823(class_3176.java:155)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.bukkit.Material
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 6 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3424932200 bytes (3266 MB) / 4607967232 bytes (4394 MB) up to 9544663040 bytes (9102 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xms1G -Xmx10G
	Data Packs: vanilla
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by iKarTehFox** [comment]
I don't know if this is helpful, but I was experiencing this same issue and ended up fixing it by switching to a later version of Java. OpenJDK 15 fixes this issue, however OpenJDK 11 has the same problem. **Don't take my word for it, as this obviously needs more testing**. It works for me, and I still don't know why.

**Comment by IsaiahPatton** [comment]
should be fixed now
