### ISSUE TITLE
Internal Exception by water bottle

### ISSUE THREAD

**Issue by jirachi1991** [CardboardPowered/cardboard#157]
I creat a new server and new world without any mod except for CardboardMod-1.16.4 and fabric-api-0.29.2+1.16

Fabric 0.11.1, server version 1.16.4

Then I join the server and take a water bottle, then drop it, then I lost connection

And server will messages : 
[Server thread/INFO]: {"Username"} lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Potion Type must not be null

Use(drink) the water bottle also happens

Thanks for made this mod, but there had some trouble

**Comment by jirachi1991** [comment]
I also get this message :
 [Server thread/WARN]: Failed to handle packet for /192.168.0.104:2890
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:498) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:219) ~[intermediary-server.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:232) ~[intermediary-server.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.IllegalArgumentException: Potion Type must not be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.potion.PotionData.<init>(PotionData.java:23) ~[CardboardMod-1.16.4.jar:?]
        at org.cardboardpowered.impl.CardboardPotionUtil.toBukkit(CardboardPotionUtil.java:86) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.craftbukkit.inventory.CraftMetaPotion.<init>(CraftMetaPotion.java:59) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:328) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.asBukkitCopy(CraftItemStack.java:72) ~[CardboardMod-1.16.4.jar:?]
        at net.minecraft.class_1309.method_6040(class_1309.java:3342) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_6040(class_3222.java:1140) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_6076(class_1309.java:2821) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2210) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:434) ~[intermediary-server.jar:?]
        ... 9 more

**Comment by jirachi1991** [comment]
If take a glass bottle and get water bottle, is fine
Use Q drop water bottle, pick up it and hold Shift key to move water bottle also fine too

Use mouse to pick up and move >> crash

**Comment by jirachi1991** [comment]
I find a new problem :
Use hopper to catch something from furnace, that thing will be disappear
And server will report : "[Server thread/INFO]: [STDERR]: java.lang.NullPointerException"

**Comment by jirachi1991** [comment]
https://www.youtube.com/watch?v=7j4KeuegxAk&feature=youtu.be
Here I made a vedio to show the  problem

**Comment by jirachi1991** [comment]
The server did not crash
But I still attach the log
[latest.log](https://github.com/CardboardPowered/cardboard/files/5990184/latest.log)

**Comment by pisaiah** [comment]
works in 1.20, assuming fixed.
