### ISSUE TITLE
Invisible chest in the minecart

### ISSUE THREAD

**Issue by Trirez** [CardboardPowered/cardboard#161]
[20:32:30] [Server thread/INFO]: [Trirez: Summoned new Minecart with Chest]
[20:32:32] [Server thread/INFO]: [STDERR]: java.lang.ClassCastException: class net.minecraft.class_1694 cannot be cast to class com.javazilla.bukkitfabric.interfaces.IMixinInventory (net.minecraft.class_1694 and com.javazilla.bukkitfabric.interfaces.IMixinInventory are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @2ed2d9cb)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1703.transferTo(class_1703.java:781)
[20:32:32] [Server thread/INFO]: [STDERR]:      at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callInventoryOpenEvent(BukkitEventFactory.java:337)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3222.handler$zbo000$openHandledScreen(class_3222.java:1792)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3222.method_17355(class_3222.java)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1693.method_5688(class_1693.java:183)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1657.method_7287(class_1657.java:1049)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_12062(class_3244.java:1304)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2824.method_12251(class_2824.java:74)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2824.method_11054(class_2824.java:13)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2600.method_11072(class_2600.java:21)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3738.run(class_3738.java:18)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18859(class_1255.java:144)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_4093.method_18859(class_4093.java:23)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_16075(class_1255.java:118)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18857(class_1255.java:127)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674)
[20:32:32] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[20:32:32] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Unknown Source)

TO DO:
Summon new minecart chest and open it and throws this log.

**Comment by Trirez** [comment]
Another thing: Effects all chest entities. Ender, trapped, normal. minecart chest. All invisible.

**Comment by pisaiah** [comment]
works in 1.20, assuming fixed.
