### ISSUE TITLE
Incompatible with SimpleAuth (Fabric)

### ISSUE THREAD

**Issue by jukefr** [CardboardPowered/cardboard#162]
It seems that [SimpleAuth](https://github.com/samolego/SimpleAuth) does some stuff to the mixins that cardboard doesn't like which results in a crash.

Can't really tell if this is SimpleAuth doing things badly or an issue on cardboard side so I will let you be the judge.

This is with latest master as build (4292797ff845de3a3086f18032666e4493040b63) for cardboard.

Here are the logs
<details>

```
[10:22:27] [main/INFO]: Loading for game Minecraft 1.16.5
[10:22:27] [main/WARN]: Warnings were found! 
 - Mod 'adventure-platform-fabric' (adventure-platform-fabric) recommends version 0.1 or later of mod colonel, which is missing!
	- You must install version 0.1 or later of colonel.
[10:22:27] [main/INFO]: [FabricLoader] Loading 78 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, org_mongodb_mongodb-driver-sync@4.1.0, fabricloader@0.11.1, net_kyori_adventure-text-serializer-gson@4.4.0, hydrogen@0.2-SNAPSHOT, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, lithium@0.6.1, fabric-dimensions-v1@2.0.2+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, fabric-permissions-api-v0@0.1-SNAPSHOT, java@11, net_kyori_adventure-text-minimessage@4.1.0-SNAPSHOT, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, net_java_dev_jna_jna@5.5.0, colorchat@1.3.2, net_kyori_adventure-text-feature-pagination@4.0.0-SNAPSHOT, fabric-textures-v0@1.0.6+ca58154a7d, adventure-platform-fabric@4.0.0-SNAPSHOT, org_iq80_leveldb_leveldb-api@0.12, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, lazydfu@0.1.1, starlight@0.0.3, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, at_favre_lib_bcrypt@0.9.0, fabric-loot-tables-v1@1.0.2+ca58154a7d, carpet-extra@1.4.23, fabric@0.29.4+1.16, carpet@1.4.27, fabric-particles-v1@0.2.4+ca58154a7d, mpsleep@1.1.0, cadmium@0.1.0-lucilletea.1, fabric-networking-v0@0.3.2+ca58154a7d, net_kyori_adventure-api@4.4.0, net_kyori_examination-api@1.0.0, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, minimotd-fabric@1.3.0+43b01fe-SNAPSHOT, minecraft@1.16.5, fabric-command-api-v1@1.0.10+ca58154a7d, net_kyori_adventure-platform-api@4.0.0-SNAPSHOT, net_kyori_adventure-text-serializer-plain@4.4.0, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, invview@1.4.0-1.16.4+, org_iq80_leveldb_leveldb@0.12, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, net_kyori_examination-string@1.0.0, fabric-entity-events-v1@1.0.3+ca58154a7d, cardboard@${version}, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, at_favre_lib_bytes@1.3.0, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, worldedit@7.2.0+a51fa43, fabric-biome-api-v1@3.1.1+ca58154a7d, simpleauth@1.7.5, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, net_kyori_adventure-key@4.4.0, de_mkammerer_argon2-jvm@2.7, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d, mixintrace@1.0.0
[10:22:27] [main/WARN]: Mod `cardboard` (${version}) does not respect SemVer - comparison support is limited.
[10:22:28] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/opt/msm/servers/bssm/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[10:22:30] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-[10:22:30] [main/WARN]: Trying to reflect-hack into the class-loader so we can defi[10:22:39] [main/FATAL]: Mixin apply failed mixins.simpleauth.json:MixinWorldSaveHandler -> net.minecraft.class_29: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_29::fileExists with priority 1000 cannot inject into net/minecraft/class_29::method_261(Lnet/minecraft/class_1657;)Lnet/minecraft/class_2487; merged by com.javazilla.bukkitfabric.mixin.world.MixinWorldSaveHandler with priority 1000 [PREINJECT Applicator Phase -> mixins.simpleauth.json:MixinWorldSaveHandler -> Prepare Injections ->  -> handler$zlm000$fileExists(Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2487;Ljava/io/File;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_29::fileExists with priority 1000 cannot inject into net/minecraft/class_29::method_261(Lnet/minecraft/class_1657;)Lnet/minecraft/class_2487; merged by com.javazilla.bukkitfabric.mixin.world.MixinWorldSaveHandler with priority 1000 [PREINJECT Applicator Phase -> mixins.simpleauth.json:MixinWorldSaveHandler -> Prepare Injections ->  -> handler$zlm000$fileExists(Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2487;Ljava/io/File;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minecraft.class_32$class_5143.method_27427(class_32.java:310) ~[intermediary[10:22:39] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
[10:22:39] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
[10:22:39] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
[10:22:39] [main/INFO]: [STDERR]: 	... 1 more
[10:22:39] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[10:22:39] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:22:39] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:22:39] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:22:39] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
[10:22:39] [main/INFO]: [STDERR]: 	... 2 more
[10:22:39] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27)
[10:22:39] [main/INFO]: [STDERR]: 	... 7 more
[10:22:39] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[10:22:39] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:22:39] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:22:39] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:22:39] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[10:22:39] [main/INFO]: [STDERR]: 	... 9 more
[10:22:39] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[10:22:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
[10:22:39] [main/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[10:22:39] [main/INFO]: [STDERR]: 	at net.minecraft.class_32$class_5143.method_27427(class_32.java:310)
[10:22:39] [main/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:279)
[10:22:39] [main/INFO]: [STDERR]: 	at net.minecraft.class_3176.<init>(class_3176.java:80)
[10:22:39] [main/INFO]: [STDERR]: 	at net.minecraft.server.Main.method_29734(Main.java:180)
[10:22:39] [main/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:260)
[10:22:39] [main/INFO]: [STDERR]: 	at net.minecraft.server.Main.main(Main.java:179)
[10:22:39] [main/INFO]: [STDERR]: 	... 14 more
[10:22:39] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.simpleauth.json:MixinWorldSaveHandler] from phase [DEFAULT] in config [mixins.simpleauth.json] FAILED during APPLY
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[10:22:39] [main/INFO]: [STDERR]: 	... 26 more
[10:22:39] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_29::fileExists with priority 1000 cannot inject into net/minecraft/class_29::method_261(Lnet/minecraft/class_1657;)Lnet/minecraft/class_2487; merged by com.javazilla.bukkitfabric.mixin.world.MixinWorldSaveHandler with priority 1000 [PREINJECT Applicator Phase -> mixins.simpleauth.json:MixinWorldSaveHandler -> Prepare Injections ->  -> handler$zlm000$fileExists(Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2487;Ljava/io/File;)V -> Prepare]
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[10:22:39] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[10:22:39] [main/INFO]: [STDERR]: 	... 26 more
```
</details>

**Comment by IsaiahPatton** [comment]
Should now be fixed in the latest update.
