### ISSUE TITLE
DangerousCaves plugin don't work

### ISSUE THREAD

**Issue by DeZoWaRe** [CardboardPowered/cardboard#175]
![8129_5ff0846ba4370](https://user-images.githubusercontent.com/71688822/111183039-8c5c3400-85c0-11eb-8ddb-eb7ae83cb675.jpg)

**Plugin version**: 2.2.13
**Version Carboard**: 152
**Fabric version**: 0.7.2
**Report**:  
`[20:01:22] [Server thread/INFO]: Enabling DangerousCaves v2.2.13;24
[20:01:22] [Server thread/FATAL]: Error occurred while enabling DangerousCaves v2.2.13;24 (Is it up to date?)
java.lang.NullPointerException: null
        at me.imdanix.caves.generator.CaveGenerator.reload(CaveGenerator.java:59) ~[?:?]
        at me.imdanix.caves.configuration.Configuration.reload(Configuration.java:80) ~[?:?]
        at me.imdanix.caves.configuration.Configuration.register(Configuration.java:61) ~[?:?]
        at me.imdanix.caves.DangerousCaves.onEnable(DangerousCaves.java:74) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:457) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:388) ~[CardboardMod-1.16.4.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:2046) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:179) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[20:01:22] [Server thread/INFO]: Disabling DangerousCaves v2.2.13;24`

**Mode installed**:
Carboard, starlight-fabric-0.0.2

**Plugin installed**: 
Dangerous-Caves-2.2.13

**Link on error plugin**: [https://www.spigotmc.org/resources/dangerous-caves-2-make-your-caves-scary-1-12-2-1-16-5.76212/](url)

**Comment by imDaniX** [comment]
For somebody in the future.
https://github.com/CardboardPowered/cardboard/blob/e93c34aef476abef9b776c1998fee1d4605b41b0/src/main/java/org/cardboardpowered/impl/world/WorldImpl.java#L775-L779
I sure can fix it on my end, but it isn't appropriate solution, just because the method is annotated as notnull. But the way I use it in the generator is kinda junky too, so, ehh, at least I'll look into it.
