### ISSUE TITLE
UltimateTimber plugin

### ISSUE THREAD

**Issue by DeZoWaRe** [CardboardPowered/cardboard#180]
![8129_5ff0846ba4370](https://user-images.githubusercontent.com/71688822/111183039-8c5c3400-85c0-11eb-8ddb-eb7ae83cb675.jpg)

**Plugin version**: 2.0.8
**Version Carboard**: 152
**Fabric version**: 0.7.2
**Report**:  

`[21:57:48] [Server thread/FATAL]: Unexpected error while loading UltimateTimber v2.0.8 c2.3.40: Disabling plugin!
java.lang.NullPointerException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at com.songoda.ultimatetimber.core.core.SongodaCoreDiagCommand.<init>(SongodaCoreDiagCommand.java:27) ~[?:?]
        at com.songoda.ultimatetimber.core.SongodaCore.init(SongodaCore.java:161) ~[?:?]
        at com.songoda.ultimatetimber.core.SongodaCore.registerPlugin(SongodaCore.java:143) ~[?:?]
        at com.songoda.ultimatetimber.core.SongodaCore.registerPlugin(SongodaCore.java:74) ~[?:?]
        at com.songoda.ultimatetimber.UltimateTimber.onPluginEnable(UltimateTimber.java:52) ~[?:?]
        at com.songoda.ultimatetimber.core.SongodaPlugin.onEnable(SongodaPlugin.java:97) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:457) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:388) ~[CardboardMod-1.16.4.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:2046) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:179) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[21:57:48] [Server thread/INFO]: Disabling UltimateTimber v2.0.8`

**Mode installed**:
Carboard, starlight-fabric-0.0.2

**Plugin installed**: 
UltimateTimber-2.0.8

**Link on error plugin**: [https://songoda.com/marketplace/product/ultimatetimber-the-realistic-tree-chopper.18](url)

**Comment by cylian914** [comment]
ists not a cardbox probleme but  a lib probleme
