### ISSUE TITLE
LightAPI Plugin Crash

### ISSUE THREAD

**Issue by DeZoWaRe** [CardboardPowered/cardboard#183]
![8129_5ff0846ba4370](https://user-images.githubusercontent.com/71688822/111183039-8c5c3400-85c0-11eb-8ddb-eb7ae83cb675.jpg)

**Plugin version**: 3.4.6
**Version Carboard**: 154
**Fabric version**: 0.7.2
**Report**:  

`[15:13:50 INFO]: [LightAPI] Enabling LightAPI v3.4.6
[15:13:50 INFO]: [Bukkit] [LightAPI] Could not find Bukkit4Fabric implementation. Trying CraftBukkit instead
[15:13:50 INFO]: [Bukkit] [LightAPI] Could not initialize CraftBukkit implementation for Bukkit4Fabric server v1_16_R3.
[15:13:50 INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[15:13:50 INFO]: [STDERR]:      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:13:50 INFO]: [STDERR]:      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:13:50 INFO]: [STDERR]:      at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:13:50 INFO]: [STDERR]:      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[15:13:50 INFO]: [STDERR]:      at ru.beykerykt.lightapi.server.ServerModManager.initImplementaion(ServerModManager.java:44)
[15:13:50 INFO]: [STDERR]:      at ru.beykerykt.lightapi.LightAPI.onEnable(LightAPI.java:227)
[15:13:50 INFO]: [STDERR]:      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:13:50 INFO]: [STDERR]:      at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[15:13:50 INFO]: [STDERR]:      at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[15:13:50 INFO]: [STDERR]:      at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:457)
[15:13:50 INFO]: [STDERR]:      at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:388)
[15:13:50 INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:2046)
[15:13:50 INFO]: [STDERR]:      at net.minecraft.class_3176.method_3823(class_3176.java:179)
[15:13:50 INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
[15:13:50 INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[15:13:50 INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:834)
[15:13:50 INFO]: [STDERR]: Caused by: java.lang.RuntimeException: (NoSuchMethodException) net.minecraft.class_3846.f()
[15:13:50 INFO]: [STDERR]:      at ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_16_R3.toRuntimeException(CraftBukkit_v1_16_R3.java:257)
[15:13:50 INFO]: [STDERR]:      at ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_16_R3.<init>(CraftBukkit_v1_16_R3.java:72)
[15:13:50 INFO]: [STDERR]:      ... 16 more
[15:13:50 INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodException: net.minecraft.class_3846.f()
[15:13:50 INFO]: [STDERR]:      at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
[15:13:50 INFO]: [STDERR]:      at ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_16_R3.<init>(CraftBukkit_v1_16_R3.java:57)
[15:13:50 INFO]: [STDERR]:      ... 16 more
[15:13:50 INFO]: [Bukkit] [LightAPI] Disabling plugin
[15:13:50 INFO]: [LightAPI] Disabling LightAPI v3.4.6`

**Mode installed**:
Carboard

**Plugin installed**: 
LightAPI Fork, InteractionVisualizer

**Link on error plugin**: [https://www.spigotmc.org/resources/lightapi-fork.48247/](url)

**Comment by cylian914** [comment]
probleme with the plugin not cardbox
