### ISSUE TITLE
InteractionVisualizer Plugin Crash

### ISSUE THREAD

**Issue by DeZoWaRe** [CardboardPowered/cardboard#184]
![8129_5ff0846ba4370](https://user-images.githubusercontent.com/71688822/111183039-8c5c3400-85c0-11eb-8ddb-eb7ae83cb675.jpg)

**Plugin version**: 1.14.5
**Version Carboard**: 154
**Fabric version**: 0.7.2
**Report**:  

`[15:13:50 INFO]: [InteractionVisualizer] Enabling InteractionVisualizer v1.14.5.4
[15:13:50 INFO]: [Bukkit] [InteractionVisualizer] Loading languages...
[15:13:50 FATAL]: [Bukkit] Error occurred while enabling InteractionVisualizer v1.14.5.4 (Is it up to date?)
java.lang.RuntimeException: Failed to find NMS class: DataWatcherRegistry
        at com.comphenix.protocol.utility.MinecraftReflection.lambda$getMinecraftClass$1(MinecraftReflection.java:2032) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2032) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getDataWatcherRegistryClass(MinecraftReflection.java:1375) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.initialize(WrappedDataWatcher.java:1001) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:939) ~[?:?]
        at com.loohp.interactionvisualizer.Protocol.WatchableCollection.setup(WatchableCollection.java:33) ~[?:?]
        at com.loohp.interactionvisualizer.InteractionVisualizer.onEnable(InteractionVisualizer.java:164) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:457) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:388) ~[CardboardMod-1.16.4.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:2046) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:179) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[15:13:50 INFO]: [InteractionVisualizer] Disabling InteractionVisualizer v1.14.5.4
[15:13:50 INFO]: [Bukkit] [InteractionVisualizer] Error while saving blockdata.json, retrying..
[15:13:50 INFO]: [Bukkit] [InteractionVisualizer] InteractionVisualizer has been disabled!`

**Mode installed**:
Carboard

**Plugin installed**: 
LightAPI Fork, InteractionVisualizer

**Link on error plugin**: [https://www.spigotmc.org/resources/interactionvisualizer-visualize-function-blocks-like-crafting-tables-with-animations-client-side.77050/](url)

**Comment by cylian914** [comment]
wow again the probleme is the plugin not cardbox
