### ISSUE TITLE
Cardboard + ImmersivePortals

### ISSUE THREAD

**Issue by Chris-Calvo** [CardboardPowered/cardboard#189]
Plugin version: 1.16.5
Version Carboard: 156
Fabric version: 0.7.3
Report:

[19:08:57] [main/INFO]: Loading for game Minecraft 1.16.5
[19:08:58] [main/INFO]: [FabricLoader] Loading 53 mods: fabric-renderer-api-v1@0.4.2+2868a2287d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.3, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, java@15, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.3.0+2868a2287d, immersive_portals@0.90, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.32.9+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, imm_ptl_core@0.90, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.5+9354966b7d, modmenu@v1.16.8+unknown.bd9230a, fabric-command-api-v1@1.1.1+351679a77d, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, cardboard@156, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.6.0+2868a2287d, cloth-config2@4.11.15, fabric-resource-loader-v0@0.4.6+2868a2287d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[19:08:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/ccalv/Downloads/FabServer/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[19:08:58] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[19:08:58] [main/WARN]: Error loading class: net/minecraft/class_634 (java.lang.ClassNotFoundException: net/minecraft/class_634)
[19:08:58] [main/WARN]: @Mixin target net.minecraft.class_634 was not found imm_ptl_fabric.mixins.json:common.MixinDebugClientPlayNetworkHandler
[19:08:58] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in imm_ptl.mixins.json:common.entity_sync.MixinEntityTracker and should be specified in value
[19:09:04] [main/INFO]: [Portal] Immersive Portals Mod Initializing
[19:09:04] [main/INFO]: [Portal] Reach entity attributes mod is not present
[19:09:04] [main/INFO]: [Portal] Pehkui is not present
[19:09:04] [main/INFO]: [Bukkit] 
[19:09:04] [main/INFO]: [Bukkit] Cardboard Mod - CardboardPowered.org
[19:09:04] [main/INFO]: [Bukkit] 
[19:09:05] [main/INFO]: [BukkitNmsRemapper] Reflection working: true
[19:09:05] [main/INFO]: [Bukkit] Cardboard mod Loaded.
[19:09:05] [main/INFO]: [Portal] initializing dedicated server
[19:09:06] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:09:06] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[19:09:06] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[19:09:06] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:09:06] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:09:06] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[19:09:06] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:09:06] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Immersive Portals, Fabric Tool Attribute API (v1))
[19:09:07] [Worker-Main-11/INFO]: Loaded 7 recipes
[19:09:07] [Worker-Main-11/INFO]: [Bukkit|RecipeManager] Loaded 7 recipes
[19:09:07] [Worker-Main-11/INFO]: Loaded 927 advancements
[19:09:08] [main/INFO]: [net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl] Applied 0 biome modifications to 0 of 79 new biomes in 1.426 ms
[19:09:08] [main/INFO]: [Portal] IP Config Applied
[19:09:08] [Server thread/INFO]: Starting minecraft server version 1.16.5
[19:09:08] [Server thread/INFO]: Loading properties
[19:09:08] [Server thread/INFO]: Default game type: SURVIVAL
[19:09:08] [Server thread/INFO]: Generating keypair
[19:09:08] [Server thread/INFO]: Starting Minecraft server on *:25565
[19:09:08] [Server thread/INFO]: Using default channel type
[19:09:08] [Server thread/INFO]: [Bukkit] Registered modded 'immersive_portals:portal_helper' as Material 'IMMERSIVE_PORTALS_PORTAL_HELPER'
[19:09:08] [Server thread/INFO]: [Bukkit] Registered modded 'immersive_portals:nether_portal_block' as Material 'IMMERSIVE_PORTALS_NETHER_PORTAL_BLOCK'
[19:09:08] [Server thread/INFO]: [Bukkit] Registered modded 'immersive_portals:command_stick' as Material 'IMMERSIVE_PORTALS_COMMAND_STICK'
**********************************************
** For some reason, these lines were not included in the log, though appeared in the CMD window. 
** Figured better safe than sorry:
** WARNING: An illegal reflective access operation has occurred
** WARNING: Illegal reflective access by com.javazilla.bukkitfabric.MakeMaterial 
** (file:/C:/Users/ccalv/Downloads/FabServer/mods/CardboardMod-1.16.4.jar) to constructor com.sun.tools.javac.api.JavacTool()
** WARNING: Please consider reporting this to the maintainers of com.javazilla.bukkitfabric.MakeMaterial
** WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
** WARNING: All illegal access operations will be denied in a future release
**********************************************
[19:09:10] [Server thread/INFO]: [Bukkit] JavaC Debug: lib\Material.java uses or overrides a deprecated API.
[19:09:10] [Server thread/INFO]: [Bukkit] JavaC Debug: lib\Material.java uses unchecked or unsafe operations.
[19:09:10] [Server thread/INFO]: [Bukkit] Adding "Cardboard-Generated-Material-Class.jar" to Knot.
[19:09:10] [Server thread/INFO]: [Bukkit] This server is running CardboardPowered.org version git-Bukkit4Fabric-1dd53b8 (MC: 1.16.5) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[19:09:10] [Server thread/INFO]: [Bukkit] Debug logging is disabled
[19:09:10] [Server thread/INFO]: [Bukkit] Server Ping Player Sample Count: {0}
[19:09:10] [Server thread/INFO]: [Bukkit] Using {0} threads for Netty based IO
[19:09:10] [Server thread/INFO]: [Bukkit] Loading Bukkit plugins...
[19:09:11] [Server thread/INFO]: [ClearLag] Loading ClearLag v3.2.2
[19:09:11] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.2.1+299386a
[19:09:11] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@409b4e47]
[19:09:11] [Server thread/INFO]: [Timber] Loading Timber v1.0.9
[19:09:11] [Server thread/INFO]: [Essentials] Loading Essentials v2.18.2.0
[19:09:11] [Server thread/INFO]: [VeinMiner] Loading VeinMiner v1.15.1
[19:09:11] [Server thread/INFO]: [SinglePlayerSleep] Loading SinglePlayerSleep v1.13_2.13.45.2
[19:09:11] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.1+299386a
[19:09:11] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[19:09:12] [Server thread/WARN]: 
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and block property-related functions.
**
** Please see https://worldedit.enginehub.org/en/latest/faq/#bukkit-adapters
**********************************************

[19:09:12] [Server thread/INFO]: [Bukkit] 
[19:09:12] [Server thread/INFO]: Preparing level "world"
[19:09:15] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:2198) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:2031) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:179) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8450()" because the return value of "net.minecraft.server.MinecraftServer.method_30002()" is null
	at net.minecraft.server.MinecraftServer.method_3767(MinecraftServer.java:1463) ~[intermediary-server.jar:?]
	at com.qouteall.imm_ptl_peripheral.altius_world.AltiusGameRule.getIsDimensionStack(AltiusGameRule.java:33) ~[immersive-portals-0.90-mc1.16.5-fabric.jar:?]
	at com.qouteall.imm_ptl_peripheral.altius_world.AltiusInfo.replaceBedrock(AltiusInfo.java:97) ~[immersive-portals-0.90-mc1.16.5-fabric.jar:?]
	at net.minecraft.class_2806.handler$zgl000$redirectBuildSurface(class_2806.java:529) ~[intermediary-server.jar:?]
	at net.minecraft.class_2806.method_16567(class_2806.java:75) ~[intermediary-server.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:263) ~[intermediary-server.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:219) ~[intermediary-server.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:568) ~[intermediary-server.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:562) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-server.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:94) ~[intermediary-server.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:137) ~[intermediary-server.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:105) ~[intermediary-server.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]

Mode installed:
Carboard

Plugin installed:
ImmersivePortals

Link on error plugin: https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod

**Comment by Chris-Calvo** [comment]
After reviewing Issue #23, these mods are NOT compatible.
