### ISSUE TITLE
When i installed the cardboard mod, i cant connect to the server anymore.

### ISSUE THREAD

**Issue by Vortex64-hmm** [CardboardPowered/cardboard#198]
Hello, I recently added cardboard to me self hosted fabric server with 4GB ram allocated and since I added it, I am no longer able to connect, minecraft just gives me the Connection Lost error and the console says I got disconnected. The server was working fine before I added the mod and I have reset the world and removed other mods to try to get it to work but I havent been able to join since i added it. Is there any way to fix this?

**Comment by bonn2** [comment]
Do you have any plugins installed?

**Comment by Vortex64-hmm** [comment]
no, not yet. I was going to add them after a sucsessfull start but it never started sucsessfully, as in i couldent connect. So no there arent any plugins at the moment.

**Comment by bonn2** [comment]
Could you post a log, can't diagnose further without one

**Comment by Vortex64-hmm** [comment]
ok

**Comment by Vortex64-hmm** [comment]
so a log from the server, or the client. because the server runs but the client is unable to connect

**Comment by Vortex64-hmm** [comment]
here is the latest.log from the server
[latest.log](https://github.com/CardboardPowered/cardboard/files/6409791/latest.log)

**Comment by Vortex64-hmm** [comment]
and from the client
[latest.log](https://github.com/CardboardPowered/cardboard/files/6409792/latest.log)

**Comment by ToatyBread** [comment]
I am having the same problem aswell, at first it came up with the internal server error, but now there is no error at all, just a cancel button.

**Comment by ToatyBread** [comment]
Do you perhaps have the antique atlas mod installed? I removed it from my server and I can join now. If not then I don't know what else could be the problem.

**Comment by Vortex64-hmm** [comment]
no i dont have any mods installed

**Comment by Cookie-Kurokami** [comment]
I've been having this same problem. Has anyone found a fix yet?

**Comment by gniftygnome** [comment]
I'm not sure if this is related but in case it helps, we use Velocity and with the same other mods installed, without Cardboard it works and with Cardboard 159 the user is immediately kicked with a similarly bland server-side log but Velocity logs the following:

[11:00:15 INFO]: [server connection] GniftyGnome -> lobby has connected
[11:00:15 ERROR]: [server connection] GniftyGnome -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.LoginSessionHandler@5523e4b1
java.lang.IllegalArgumentException: Duplicate handler name: compression-decoder
        at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[velocity-1.1.3.jar:1.1.3]
        at com.velocitypowered.proxy.connection.MinecraftConnection.setCompressionThreshold(MinecraftConnection.java:393) ~[velocity-1.1.3.jar:1.1.3]
        at com.velocitypowered.proxy.connection.backend.LoginSessionHandler.handle(LoginSessionHandler.java:83) ~[velocity-1.1.3.jar:1.1.3]
        at com.velocitypowered.proxy.protocol.packet.SetCompression.handle(SetCompression.java:47) ~[velocity-1.1.3.jar:1.1.3]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:121) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-1.1.3.jar:1.1.3]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:40) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-1.1.3.jar:1.1.3]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:70) ~[velocity-1.1.3.jar:1.1.3]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:41) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-1.1.3.jar:1.1.3]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-1.1.3.jar:1.1.3]
        at java.lang.Thread.run(Thread.java:829) [?:?]
[11:00:15 INFO]: [server connection] GniftyGnome -> lobby has disconnected

**Comment by gniftygnome** [comment]
FYI, Cardboard 160 resolves the problem I mentioned above.  It might be worthwhile for others to re-test.

**Comment by Vortex64-hmm** [comment]
ok
thanks!
