### ISSUE TITLE
Citizens reflection error

### ISSUE THREAD

**Issue by BradBot1** [CardboardPowered/cardboard#202]
When enabling the Citizens plugin the following exception is thrown
```
[18:10:36 FATAL]: [Bukkit] Error occurred while enabling Citizens v2.0.27-SNAPSHOT (build 2297) (Is it up to date?)
java.lang.ClassFormatError: Illegal method name "net.minecraft.class_2143" in class net/citizensnpcs/nms/v1_16_R3/util/NMSImpl
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_291]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_291]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_291]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:178) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[CardboardMod-1.16.4.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_291]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_291]
        at net.citizensnpcs.util.NMS.loadBridge(NMS.java:321) ~[?:?]
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:301) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:457) ~[CardboardMod-1.16.4.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:388) ~[CardboardMod-1.16.4.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:2046) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:179) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[18:10:36 INFO]: [Citizens] Disabling Citizens v2.0.27-SNAPSHOT (build 2297)
```

**Comment by Obydux** [comment]
Try using this Fabric mod for Citizens instead : https://modrinth.com/mod/taterzens

**Comment by BradBot1** [comment]
> Try using this Fabric mod for Citizens instead : https://modrinth.com/mod/taterzens

That is not possible as many of the plugins I use require the CitizensAPI

**Comment by nolway** [comment]
Yes like @BradBot1 many plugins needs citizens like BetonQuest
