### ISSUE TITLE
Fabric 1.16 crashed on JAVA 16

### ISSUE THREAD

**Issue by SimonShiki** [CardboardPowered/cardboard#220]
[23:23:46] [main/INFO]: Loading for game Minecraft 1.16.5
[23:23:46] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[23:24:03] [main/INFO]: [FabricLoader] Loading 57 mods:
	- cardboard@165
	- cloth-basic-math@0.5.1
	- cloth-config2@4.11.15
	- fabric@0.36.0+1.16
	- fabric-api-base@0.3.0+c88702897d
	- fabric-api-lookup-api-v1@1.2.0+6aebe11a7d
	- fabric-biome-api-v1@3.1.10+3661eaa17d
	- fabric-blockrenderlayer-v1@1.1.5+ca58154a7d
	- fabric-command-api-v1@1.1.1+351679a77d
	- fabric-commands-v0@0.2.2+ca58154a7d
	- fabric-containers-v0@0.1.11+9354966b7d
	- fabric-content-registries-v0@0.2.1+ca58154a7d
	- fabric-crash-report-info-v1@0.1.3+ca58154a7d
	- fabric-dimensions-v1@2.0.6+61336ba97d
	- fabric-entity-events-v1@1.1.0+c88702897d
	- fabric-events-interaction-v0@0.4.3+f941baf07d
	- fabric-events-lifecycle-v0@0.2.1+ca58154a7d
	- fabric-game-rule-api-v1@1.0.6+ca58154a7d
	- fabric-item-api-v1@1.2.1+ca58154a7d
	- fabric-item-groups-v0@0.2.7+2868a2287d
	- fabric-key-binding-api-v1@1.0.4+9354966b7d
	- fabric-keybindings-v0@0.2.1+ca58154a7d
	- fabric-lifecycle-events-v1@1.2.1+ca58154a7d
	- fabric-loot-tables-v1@1.0.2+ca58154a7d
	- fabric-mining-levels-v0@0.1.3+ca58154a7d
	- fabric-models-v0@0.3.0+bc7a746f7d
	- fabric-networking-api-v1@1.0.3+e3c9d0627d
	- fabric-networking-blockentity-v0@0.2.8+ca58154a7d
	- fabric-networking-v0@0.3.2+ca58154a7d
	- fabric-object-builder-api-v1@1.9.5+c88702897d
	- fabric-object-builders-v0@0.7.2+ca58154a7d
	- fabric-particles-v1@0.2.4+ca58154a7d
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.4+ca58154a7d
	- fabric-renderer-api-v1@0.4.3+0ef801b67d
	- fabric-renderer-indigo@0.4.4+ca58154a7d
	- fabric-renderer-registries-v1@2.3.0+2868a2287d
	- fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d
	- fabric-rendering-fluids-v1@0.1.13+ca58154a7d
	- fabric-rendering-v0@1.1.2+ca58154a7d
	- fabric-rendering-v1@1.6.0+2868a2287d
	- fabric-resource-loader-v0@0.4.6+2868a2287d
	- fabric-screen-api-v1@1.0.0+c045166c7d
	- fabric-screen-handler-api-v1@1.1.5+9354966b7d
	- fabric-structure-api-v1@1.1.11+ca0ef93d7d
	- fabric-tag-extensions-v0@1.1.1+ca58154a7d
	- fabric-textures-v0@1.0.6+ca58154a7d
	- fabric-tool-attribute-api-v1@1.2.7+8183d3957d
	- fabricloader@0.11.6
	- imm_ptl_core@0.99
	- immersive_portals@0.99
	- java@16
	- lithium@0.6.6
	- minecraft@1.16.5
	- modmenu@v1.16.8+unknown.bd9230a
	- phosphor@0.7.2+build.12
	- spark@1.6.0
[23:24:03] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/root/mcsmanager/server/server_core/KittenCraft/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[23:24:03] [main/INFO]: Compatibility level set to JAVA_16
[23:25:12] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[23:25:12] [main/WARN]: Error loading class: net/minecraft/class_634 (java.lang.ClassNotFoundException: net/minecraft/class_634)
[23:25:12] [main/WARN]: @Mixin target net.minecraft.class_634 was not found imm_ptl_fabric.mixins.json:common.MixinDebugClientPlayNetworkHandler
[23:25:12] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in imm_ptl.mixins.json:common.entity_sync.MixinEntityTracker and should be specified in value
[23:25:21] [main/WARN]: Method overwrite conflict for get in bukkitfabric.mixins.json:network.MixinServerPlayNetworkHandler_ChatEvent, previously written by org.cardboardpowered.mixin.network.MixinServerPlayNetworkHandler. Skipping method.
[23:25:21] [main/WARN]: Method overwrite conflict for method_31277 in bukkitfabric.mixins.json:network.MixinServerPlayNetworkHandler_ChatEvent, previously written by org.cardboardpowered.mixin.network.MixinServerPlayNetworkHandler. Skipping method.
] [pool-4-thread-1/INFO]: [Cardboard] Downloaded org.xerial:sqlite-jdbc:3.21.0.1.
[23:25:10] [pool-4-thread-1/ERROR]: [Cardboard] The checksum for the library 'sqlite-jdbc-3.21.0.1.jar' does not match. Attempting download again (2/2)
[23:25:10] [pool-4-thread-1/INFO]: [Cardboard] Downloading org.xerial:sqlite-jdbc:3.21.0.1...
[23:25:10] [pool-4-thread-7/INFO]: [Cardboard] Downloaded org.jline:jline:3.19.0.
[23:25:10] [pool-4-thread-7/ERROR]: [Cardboard] The checksum for the library 'jline-3.19.0.jar' does not match. Attempting download again (2/2)
[23:25:10] [pool-4-thread-7/INFO]: [Cardboard] Downloading org.jline:jline:3.19.0...
[23:25:10] [pool-4-thread-2/INFO]: [Cardboard] Downloaded mysql:mysql-connector-java:5.1.46.
[23:25:10] [pool-4-thread-2/ERROR]: [Cardboard] The checksum for the library 'mysql-connector-java-5.1.46.jar' does not match. Attempting download again (2/2)
[23:25:10] [pool-4-thread-2/INFO]: [Cardboard] Downloading mysql:mysql-connector-java:5.1.46...
[23:25:11] [main/INFO]: [Lithium] Loaded configuration file for Lithium: 80 options available, 1 override(s) found
[23:25:11] [pool-4-thread-1/WARN]: [Cardboard] Failed to download: org.xerial:sqlite-jdbc:3.21.0.1
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199) ~[?:?]
	at sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:168) ~[?:?]
	at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:392) ~[?:?]
	at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:776) ~[?:?]
	at org.cardboardpowered.library.LibraryManager$LibraryDownloader.run(LibraryManager.java:135) ~[CardboardMod-1.16.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:25:11] [pool-4-thread-1/WARN]: [Cardboard] Restart the server to attempt downloading 'sqlite-jdbc-3.21.0.1.jar' again.
[23:25:11] [main/WARN]: [Lithium] Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [immersive_portals]) disables it and children
[23:25:12] [pool-4-thread-7/WARN]: [Cardboard] Failed to download: org.jline:jline:3.19.0
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199) ~[?:?]
	at sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:168) ~[?:?]
	at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:392) ~[?:?]
	at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:776) ~[?:?]
	at org.cardboardpowered.library.LibraryManager$LibraryDownloader.run(LibraryManager.java:135) ~[CardboardMod-1.16.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:25:12] [pool-4-thread-7/WARN]: [Cardboard] Restart the server to attempt downloading 'jline-3.19.0.jar' again.
[23:25:12] [pool-4-thread-2/WARN]: [Cardboard] Failed to download: mysql:mysql-connector-java:5.1.46
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199) ~[?:?]
	at sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:168) ~[?:?]
	at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:392) ~[?:?]
	at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:776) ~[?:?]
	at org.cardboardpowered.library.LibraryManager$LibraryDownloader.run(LibraryManager.java:135) ~[CardboardMod-1.16.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:25:12] [pool-4-thread-2/WARN]: [Cardboard] Restart the server to attempt downloading 'mysql-connector-java-5.1.46.jar' again.
[23:25:22] [main/INFO]: [Portal] Immersive Portals Mod Initializing
[23:25:22] [main/INFO]: [Portal] Reach entity attributes mod is not present
[23:25:22] [main/INFO]: [Portal] Pehkui is not present
[23:25:22] [main/INFO]: [Bukkit] 
[23:25:22] [main/INFO]: [Bukkit] Cardboard Mod - CardboardPowered.org
[23:25:22] [main/INFO]: [Bukkit] 
[23:25:25] [main/INFO]: [BukkitNmsRemapper] Reflection working: true
[23:25:25] [main/INFO]: [Bukkit] Cardboard mod Loaded.
[23:25:25] [main/INFO]: [Portal] initializing dedicated server
[23:25:27] [main/ERROR]: Failed to load properties from file: server.properties
[23:25:27] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:25:27] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[23:25:29] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:25:29] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:25:29] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:25:29] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:25:29] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:25:29] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Immersive Portals, Fabric Tool Attribute API (v1))
[23:25:32] [Worker-Main-2/INFO]: Loaded 7 recipes
[23:25:32] [Worker-Main-2/INFO]: [Bukkit|RecipeManager] Loaded 7 recipes
[23:25:33] [Worker-Main-2/INFO]: Loaded 927 advancements
[23:25:35] [main/INFO]: [net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl] Applied 0 biome modifications to 0 of 79 new biomes in 3.271 ms
[23:25:36] [main/INFO]: [Portal] IP Config Applied
[23:25:36] [Server thread/INFO]: Starting minecraft server version 1.16.5
[23:25:36] [Server thread/INFO]: Loading properties
[23:25:36] [Server thread/INFO]: Default game type: SURVIVAL
[23:25:36] [Server thread/INFO]: Generating keypair
[23:25:36] [Server thread/INFO]: Starting Minecraft server on *:25565
[23:25:37] [Server thread/INFO]: Using epoll channel type
[23:25:37] [Server thread/INFO]: [Bukkit] Registering modded blocks from mod 'immersive_portals'..
[23:25:38] [Server thread/INFO]: [Bukkit] This server is running CardboardPowered.org version git-Bukkit4Fabric-672f086 (MC: 1.16.5) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[23:25:38] [Server thread/INFO]: [Bukkit] Debug logging is disabled
[23:25:38] [Server thread/INFO]: [Bukkit] Using {0} threads for Netty based IO
[23:25:38] [Server thread/INFO]: [Bukkit] Server Ping Player Sample Count: {0}
[23:25:38] [Server thread/INFO]: [Bukkit] Loading Bukkit plugins...
[23:25:38] [Server thread/INFO]: [Bukkit] 
[23:25:38] [Server thread/INFO]: Preparing level "world"
[23:25:44] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:2202) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:2020) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:179) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8450()" because the return value of "net.minecraft.server.MinecraftServer.method_30002()" is null
	at net.minecraft.server.MinecraftServer.method_3767(MinecraftServer.java:1463) ~[intermediary-server.jar:?]
	at com.qouteall.imm_ptl_peripheral.altius_world.AltiusGameRule.getIsDimensionStack(AltiusGameRule.java:33) ~[immersive-portals-0.99-mc1.16.5-fabric.jar:?]
	at com.qouteall.imm_ptl_peripheral.altius_world.AltiusInfo.replaceBedrock(AltiusInfo.java:97) ~[immersive-portals-0.99-mc1.16.5-fabric.jar:?]
	at net.minecraft.class_2806.handler$zle000$redirectBuildSurface(class_2806.java:1029) ~[intermediary-server.jar:?]
	at net.minecraft.class_2806.method_16567(class_2806.java:75) ~[intermediary-server.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:263) ~[intermediary-server.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:219) ~[intermediary-server.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:568) ~[intermediary-server.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:562) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-server.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:94) ~[intermediary-server.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:137) ~[intermediary-server.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:105) ~[intermediary-server.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
[23:25:44] [Server thread/ERROR]: This crash report has been saved to: /root/mcsmanager/server/server_core/KittenCraft/./crash-reports/crash-2021-06-27_23.25.44-server.txt
[23:25:44] [Server thread/INFO]: Stopping server
[23:25:44] [Server thread/INFO]: Saving players
[23:25:44] [Server thread/INFO]: Saving worlds
[23:25:44] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "☃" is null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:572) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:599) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:567) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:707) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:25:44] [Server thread/INFO]: [Bukkit] Goodbye!

**Comment by IsaiahPatton** [comment]
Currently incompatible with Immersive Portals.

**Comment by SinanGentoo** [comment]
> Currently incompatible with Immersive Portal
Hmm...
Could you make a list of mods that can coexist with Cardboard?
