### ISSUE TITLE
Integrated server crashes on 1.17 when loading

### ISSUE THREAD

**Issue by TheGamer1002** [CardboardPowered/cardboard#222]
I'm running Minecraft 1.17 from MultiMC on Xubuntu 20.04 LTS with OpenJDK 16 on the latest build (#20), and Minecraft hangs when loading a world. I've tried disabling my plugins for Bukkit to no avail. I do have OptiFabric among other things, however it seems that isn't the problem. Crash logs below.
<details>
<summary>Crash log</summary>

```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/29/21, 10:56 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.CraftServer.getGenerator(String)" because "org.bukkit.craftbukkit.CraftServer.INSTANCE" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer:2532)
	at net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer:85)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:274)
	at java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$bko000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:47)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Linux (amd64) version 5.4.0-77-generic
	Java Version: 16.0.1, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 5397687296 bytes (5147 MiB) / 7147094016 bytes (6816 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX(tm)-8350 Eight-Core Processor
	Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
	Microarchitecture: Piledriver
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: GM206 [GeForce GTX 960]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1401
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 111429.78
	Virtual memory used (MB): 10187.38
	Swap memory total (MB): 95397.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms163m -Xmx16384m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		amecsapi: Amecs API 1.1.4+mc21w16a
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.0.16
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bedspreads: Bedspreads 1.4.0-1.17
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betterf3: BetterF3 1.1.5
		betternether: Better Nether 5.1.0
		betterthirdperson: Better Third Person 1.5.0
		blast: BLAST 1.6.2
		blockus: Blockus 2.2.3+1.17
		blue_endless_jankson: jankson 1.2.1
		bno: Basic Nether Ores 1.17-6.0.0-Fabric
		cardboard: CardboardMod 20
		cardinal-components-base: Cardinal Components API (base) 3.0.0-nightly.1.17-pre2
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.0-nightly.1.17-pre2
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0-nightly.1.17-pre2
		cardinal-components-item: Cardinal Components API (items) 3.0.0-nightly.1.17-pre2
		cardinal-components-level: Cardinal Components API (world saves) 3.0.0-nightly.1.17-pre2
		cardinal-components-util: Cardinal Components API (utilities) 3.0.0-nightly.1.17-pre2
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0-nightly.1.17-pre2
		carrier: Carrier 1.8.0
		castle_dungeons: Castle Dungeons 2.3-1.17-fabric
		caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld: Caves and Cliffs add-on for William Wythers Overhauled Overworld 1.0
		cherishedworlds: Cherished Worlds 1.4.1-1.17
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		cmdkeybind: Command Macros 1.5.2-1.17
		com_flowpowered_flow-math: flow-math 1.0.3
		com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
		croptopia: Croptopia ${mod_version}
		dawn: Dawn API 2.0.3
		diggusmaximus: Diggus Maximus 1.4.5-1.17
		dimdoors: DimensionalDoors 4.0.0+beta.2-11.06.2021
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		easiervillagertrading: EasierVillagerTrading 1.17-fabric0.34.9-1.5.4
		expandedstorage: Expanded Storage 7.0.0-alpha.31
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463a0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b4463a0
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121a0
		fabricloader: Fabric Loader 0.11.6
		fallingtree: FallingTree 2.12.0
		fatxporbs: Fat Experience Orbs 1.0.0
		fiber: fiber 0.23.0-2
		gateofbabylon: Gate Of Babylon 1.5.0-1.17
		gbfabrictools: GBfabrictools 1.3.4+1.17
		hugestructureblocks: Huge Structure Blocks 1.0.2
		improved-stations: Improved Stations 2.0.6
		inmis: Inmis 2.3.1-1.17
		inventoryhud: Inventory HUD + 3.3.2
		inventorysorter: Inventory Sorter 1.7.9-1.17
		java: OpenJDK 64-Bit Server VM 16
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdacontrols: LambdaControls 1.7.1+1.17
		libcd: LibCapableData 3.0.3+1.16.3
		matrix: Matrix 1.0.0
		minecraft: Minecraft 1.17
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 2.0.2
		more-structures-add-on-for-william-wythers-overhauled-overworld: More Structures add-on for William Wythers Overhauled Overworld 1.1
		mostructures: Mo' Structures 1.2.1-1.17
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17-rc1
		namepain: Name Pain 1.4.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		omega-config: OmegaConfig 1.0.8
		optifabric: OptiFabric 1.11.9
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		patchouli: Patchouli 1.17-54-FABRIC
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		prefab: Prefab 2.0.0
		promenade: Promenade 2.1.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.2-beta+build.38
		repurposed_structures: Repurposed Structures 2.0.0+1.17.0
		roughlyenoughitems: Roughly Enough Items 6.0.260-alpha
		seedy-behavior: Seedy Behavior 1.0.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.0+1.17
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.0
		spruceui: SpruceUI 3.2.0+1.17
		stoneholm: Stoneholm 1.2.7
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 5.0.2-beta+build.38
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		torohealth: ToroHealth Damage Indicators 1.17-fabric-5
		tweed: Tweed 3.0.0-beta.26
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.3
		world_blender: World Blender 3.0.4+1.17.0
		worldedit: WorldEdit 7.2.6-SNAPSHOT+5833-a57f66f
		wthit: wthit 3.6.1
		xaerominimap: Xaero's Minimap 21.12.2
		xaeroworldmap: Xaero's World Map 1.14.4
	Player Count: 0 / 8; []
	Data Packs: vanilla, dimdoors/default, dimdoors/classic, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	OptiFine Version: OptiFine_1.17_HD_U_G9_pre24
	OptiFine Build: 20210628-002230
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-v1.0.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 465.27
	OpenGlRenderer: NVIDIA GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
	Suspected Mods: Unknown

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17
	OptiFine jar version: OptiFine_1.17_HD_U_G9_pre24
	OptiFine jar status: Valid OptiFine mod
	OptiFine remapped jar: ~/MultiMC/instances/1.17, but with nicer terrain/.minecraft/.optifine/OptiFine_1.17_HD_U_G9_pre24/Optifine-mapped.jar
	OptiFabric error: <None>
```

</details>

I may also be completely oblivious to the problem. Help?

**Comment by PapiOphidian** [comment]
Cardboard can't be run on the client. It's a server only mod

**Comment by MAX-XiaoKui** [comment]
@PapiOphidian When load 1.17.1 server, it crashes, the crash report is similar.

**Comment by IsaiahPatton** [comment]
Does not support the integrated server only dedicated.
