### ISSUE TITLE
Still crashes when using OpenJ9

### ISSUE THREAD

**Issue by MAX-XiaoKui** [CardboardPowered/cardboard#232]
MC `1.17.1`
Fabric loader `0.11.6`
Cardboard `#25`
log
````py
[21:09:27] [main/INFO]: Loading for game Minecraft 1.17.1
[21:09:27] [main/INFO]: [FabricLoader] Loading 8 mods:
	- cardboard@25
	- fabric-api-base@0.3.0+a02b446313
	- fabric-networking-api-v1@1.0.12+6cefd57713
	- fabric-screen-handler-api-v1@1.1.8+a02b446313
	- fabricloader@0.11.6
	- icommon-17@1.17
	- java@16
	- minecraft@1.17.1
[21:09:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/F:/Documents/GitHub/skimit-server-fabric/server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[21:09:28] [main/INFO]: Compatibility level set to JAVA_16
[21:09:28] [main/INFO]: Loading Libraries...
[21:09:29] [main/INFO]: =======================================================
[21:09:29] [main/INFO]:  iCommon - Isaiah's common library for Fabric Mods.
[21:09:29] [main/INFO]:  Copyright (c) 2018-2021. Running on MC 1.17.1 (756)
[21:09:29] [main/INFO]: =======================================================
[21:09:29] [main/INFO]: Loading...
[21:09:31] [main/INFO]: Applying mixin: MixinMinecraftServer...
[21:09:31] [main/INFO]: Applying mixin: R1_17.MixinNbtTag...
[21:09:31] [main/INFO]: Applying mixin: R1_17.MixinBlockEntity...
[21:09:31] [main/INFO]: Applying mixin: R1_17.MixinChestBlockEntity...
[21:09:31] [main/INFO]: Applying mixin: R1_17.MixinScreenHandler...
[21:09:31] [main/INFO]: Applying mixin: R1_17.MixinChunkGenerator...
[21:09:31] [main/INFO]: Applying mixin: R1_17.MixinPersistentStateManager...
[21:09:41] [main/INFO]: iCommon Mod initialized.
[21:09:41] [main/INFO]: 
[21:09:41] [main/INFO]: Cardboard - CardboardPowered.org
[21:09:41] [main/INFO]: 
[21:09:41] [main/INFO]: Registered '1' iCommon events.
[21:09:43] [main/INFO]: Reflection working: true
[21:09:43] [main/INFO]: Cardboard mod Loaded.
[21:09:44] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:09:46] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:09:46] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:09:46] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:09:46] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:09:46] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:09:46] [main/INFO]: Reloading ResourceManager: Default, bukkit
[21:09:48] [Worker-Main-12/INFO]: Loaded 7 recipes
[21:09:48] [Worker-Main-12/INFO]: Loaded 7 recipes
[21:09:49] [Worker-Main-12/INFO]: Loaded 1137 advancements
[21:09:52] [Server thread/INFO]: Starting minecraft server version 1.17.1
[21:09:52] [Server thread/INFO]: Loading properties
[21:09:52] [Server thread/INFO]: Default game type: SURVIVAL
[21:09:52] [Server thread/INFO]: Generating keypair
[21:09:52] [Server thread/INFO]: Starting Minecraft server on *:10894
[21:09:52] [Server thread/INFO]: Using default channel type
[21:09:54] [Server thread/INFO]: [STDOUT]: Cardboard currently does not work with Eclipse OpenJ9
[21:09:54] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
	at java.lang.J9VMInternals.ensureError(Unknown Source) ~[?:?]
	at java.lang.J9VMInternals.recordInitializationFailure(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.util.CraftMagicNumbers.test(CraftMagicNumbers.java:202) ~[%5BBukkit插件支持%5DCardboardMod-1.17.jar:?]
	at net.minecraft.class_3176.handler$zza000$init(class_3176.java:762) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:160) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$4017/0x000000005b66de20.run(Unknown Source) [intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: java.lang.NoSuchFieldException: enumConstantDirectory
	at io.izzel.arclight.api.EnumHelper.<clinit>(EnumHelper.java:96) ~[%5BBukkit插件支持%5DCardboardMod-1.17.jar:?]
	... 7 more
Caused by: java.lang.NoSuchFieldException: enumConstantDirectory
	at java.lang.Class.getDeclaredFieldInternal(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:?]
	at io.izzel.arclight.api.EnumHelper.<clinit>(EnumHelper.java:90) ~[%5BBukkit插件支持%5DCardboardMod-1.17.jar:?]
	... 7 more
[21:09:55] [Server thread/ERROR]: This crash report has been saved to: F:\Documents\GitHub\skimit-server-fabric\server\.\crash-reports\crash-2021-07-23_21.09.55-server.txt
[21:09:55] [Server thread/INFO]: Stopping server
[21:09:55] [Server thread/INFO]: Saving worlds
[21:09:55] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "???" is null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:588) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:624) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:585) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:734) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$4017/0x000000005b66de20.run(Unknown Source) [intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[21:09:55] [Server thread/INFO]: Goodbye!
````
crash-report
````sql
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2021/7/23 下午9:09
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(Unknown Source)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(Unknown Source)
	at org.bukkit.craftbukkit.util.CraftMagicNumbers.test(CraftMagicNumbers.java:202)
	at net.minecraft.class_3176.handler$zza000$init(class_3176.java:762)
	at net.minecraft.class_3176.method_3823(class_3176.java:160)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at net.minecraft.server.MinecraftServer$$Lambda$4017/0x000000005b66de20.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: java.lang.NoSuchFieldException: enumConstantDirectory
	at io.izzel.arclight.api.EnumHelper.<clinit>(EnumHelper.java:96)
	... 7 more
Caused by: java.lang.NoSuchFieldException: enumConstantDirectory
	at java.base/java.lang.Class.getDeclaredFieldInternal(Unknown Source)
	at java.base/java.lang.Class.getDeclaredField(Unknown Source)
	at io.izzel.arclight.api.EnumHelper.<clinit>(EnumHelper.java:90)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: Eclipse OpenJ9 VM (JRE 16 Windows 10 amd64-64-Bit Compressed References 20210507_34 (JIT enabled, AOT enabled)
OpenJ9   - 1e9235835
OMR      - 7bff18ff5
JCL      - 7a506c7025 based on jdk-16.0.1+9), Eclipse OpenJ9
	Memory: 86780584 bytes (82 MiB) / 660078592 bytes (629 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 750 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1380
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
	Graphics card #1 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1c03
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7141
	Graphics card #2 name: Intel(R) HD Graphics 630
	Graphics card #2 vendor: Intel Corporation (0x8086)
	Graphics card #2 VRAM (MB): 1024.00
	Graphics card #2 deviceId: 0x5912
	Graphics card #2 versionInfo: DriverVersion=27.20.100.8681
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Virtual memory max (MB): 65455.07
	Virtual memory used (MB): 38964.60
	Swap memory total (MB): 40960.00
	Swap memory used (MB): 6740.41
	JVM Flags: 4 total; -Xoptionsfile=C:\Program Files\AdoptOpenJDK\jre-16.0.1.9-openj9\lib\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Xmx2G
	Data Packs: vanilla, file/bukkit (incompatible)
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
````

**Comment by 1a2s3d4f1** [comment]
此pull不在1.17分支里面，所以崩溃了
https://github.com/CardboardPowered/cardboard/blob/1.17-dev/src/main/java/io/izzel/arclight/api/EnumHelper.java
里面没包含J9兼容修复

**Comment by MAX-XiaoKui** [comment]
好的，谢谢
