### ISSUE TITLE
Conflict Architectury API [1.16.5]

### ISSUE THREAD

**Issue by Anhelm** [CardboardPowered/cardboard#259]
Good afternoon. Conflict with Architecture and plugin detected EssentialsXChat-2.19.0-dev+26-ea7ffd2.jar.
Plugin taken from your site.
When adding the Architecture mod, the prefixes and colors in the chat stop working.
![image](https://user-images.githubusercontent.com/74124042/131827507-1992a85f-4553-422e-832a-b99470a96612.png)
Version architecture: [Fabric 1.16.4/5] v1.22.32
Version Cardboard: Cardboard 1.16-#169 (for 1.16.5)

**Comment by Anhelm** [comment]
Now version error 170
[latest.log](https://github.com/CardboardPowered/cardboard/files/7114450/latest.log)

**Comment by Anhelm** [comment]
Checked, removed all mods, started. Added Architecture and gives a server startup error.
[latest.log](https://github.com/CardboardPowered/cardboard/files/7114487/latest.log)

**Comment by Anhelm** [comment]
Updated KubeJS  and Rhino to the latest versions, now such a bug.
[latest.log](https://github.com/CardboardPowered/cardboard/files/7114548/latest.log)

**Comment by Anhelm** [comment]
Server console text:
```
itectury.mixins.json:PlayerAttackInvoker
[15:56:17] [main/INFO]: Looking for KubeJS plugins...
[15:56:17] [main/INFO]: Found kubejs plugin
[15:56:17] [main/INFO]: Done in 0 s
[15:56:17] [main/INFO]: Loaded common.properties
[15:56:17] [main/WARN]: @Final field field_9194:Ljava/util/Map; in bukkitfabric.
mixins.json:MixinExplosion should be final
[15:56:17] [main/INFO]: Hello, World! (You will only see this line once in conso
le, during startup)
[15:56:17] [main/INFO]: Loaded script startup_scripts:script.js in 0.052 s
[15:56:17] [main/INFO]: Loaded 1/1 KubeJS startup scripts in 0.333 s
[15:56:18] [main/INFO]:
[15:56:18] [main/INFO]: Cardboard Mod - CardboardPowered.org
[15:56:18] [main/INFO]:
[15:56:19] [main/INFO]: Reflection working: true
[15:56:19] [main/INFO]: Cardboard mod Loaded.
[15:56:20] [main/INFO]: Environment: authHost='https://authserver.mojang.com', a
ccountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.
com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:56:21] [main/WARN]: Ambiguity between arguments [teleport, destination] and
[teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c0
1849e498]
[15:56:21] [main/WARN]: Ambiguity between arguments [teleport, location] and [te
leport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:56:21] [main/WARN]: Ambiguity between arguments [teleport, location] and [te
leport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:56:21] [main/WARN]: Ambiguity between arguments [teleport, targets] and [tel
eport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849
e498]
[15:56:21] [main/WARN]: Ambiguity between arguments [teleport, targets, location
] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:56:21] [main/INFO]: Hello, World! (You will see this line every time server
resources reload)
[15:56:21] [main/INFO]: Loaded script server_scripts:script.js in 0.003 s
[15:56:21] [main/INFO]: Loaded 1/1 KubeJS server scripts in 0.014 s
[15:56:21] [main/INFO]: Scripts loaded
[15:56:21] [main/INFO]: Registered custom recipe handler for type minecraft:craf
ting_shaped
[15:56:21] [main/INFO]: Registered custom recipe handler for type minecraft:craf
ting_shapeless
[15:56:21] [main/INFO]: Registered custom recipe handler for type minecraft:ston
ecutting
[15:56:21] [main/INFO]: Registered custom recipe handler for type minecraft:smel
ting
[15:56:21] [main/INFO]: Registered custom recipe handler for type minecraft:blas
ting
[15:56:21] [main/INFO]: Registered custom recipe handler for type minecraft:smok
ing
[15:56:21] [main/INFO]: Registered custom recipe handler for type minecraft:camp
fire_cooking
[15:56:21] [main/INFO]: Registered custom recipe handler for type minecraft:smit
hing
[15:56:21] [main/INFO]: Scanning recipes...
[15:56:21] [main/INFO]: Reloading ResourceManager: KubeJS Virtual Data Pack [low
 priority], Default, Fabric Mods (KubeJS, Fabric Tool Attribute API (v1)), KubeJ
S Resource Pack [data], KubeJS Virtual Data Pack [high priority]
[15:56:22] [Worker-Main-7/INFO]: [blocks] Found 86 tags, added 0 objects, remove
d 0 objects
[15:56:22] [Worker-Main-7/INFO]: [items] Found 60 tags, added 0 objects, removed
 0 objects
[15:56:22] [Worker-Main-7/INFO]: [fluids] Found 2 tags, added 0 objects, removed
 0 objects
[15:56:22] [Worker-Main-7/INFO]: [entity_types] Found 5 tags, added 0 objects, r
emoved 0 objects
[15:56:22] [Worker-Main-7/INFO]: Found 859 recipes and 0 failed recipes in 98.09
 ms
[15:56:22] [Worker-Main-7/INFO]: Posted recipe events in 1.320 ms
[15:56:22] [Worker-Main-7/INFO]: Modified & removed recipes in 37.10 ms
[15:56:22] [Worker-Main-7/INFO]: Added recipes in 1.484 ms
[15:56:22] [Worker-Main-7/INFO]: Added 0 recipes, removed 0 recipes, modified 0
recipes, with 0 failed recipes and 0 fall-backed recipes
[15:56:22] [Worker-Main-7/INFO]: [functions] Found 0 tags, added 0 objects, remo
ved 0 objects
[15:56:22] [Worker-Main-7/INFO]: Loaded 927 advancements
[15:56:23] [main/INFO]: Applied 158 biome modifications to 79 of 79 new biomes i
n 21.10 ms
[15:56:23] [main/FATAL]: Mixin apply failed bukkitfabric.mixins.json:network.Mix
inPlayerManager_ChatEvent -> net.minecraft.class_3324: org.spongepowered.asm.mix
in.injection.throwables.InvalidInjectionException Critical injection failure: @I
nject annotation on cardboard_doChatEvent_PLRMGR could not find any targets matc
hing 'broadcast' in net.minecraft.class_3324. Using refmap CardboardMod-refmap.j
son [PREINJECT Applicator Phase -> bukkitfabric.mixins.json:network.MixinPlayerM
anager_ChatEvent -> Prepare Injections ->  -> handler$zcp000$cardboard_doChatEve
nt_PLRMGR(Lnet/minecraft/class_2561;Ljava/util/function/Function;Lnet/minecraft/
class_2556;Ljava/util/UUID;Lorg/spongepowered/asm/mixin/injection/callback/Callb
ackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Crit
ical injection failure: @Inject annotation on cardboard_doChatEvent_PLRMGR could
 not find any targets matching 'broadcast' in net.minecraft.class_3324. Using re
fmap CardboardMod-refmap.json [PREINJECT Applicator Phase -> bukkitfabric.mixins
.json:network.MixinPlayerManager_ChatEvent -> Prepare Injections ->  -> handler$
zcp000$cardboard_doChatEvent_PLRMGR(Lnet/minecraft/class_2561;Ljava/util/functio
n/Function;Lnet/minecraft/class_2556;Ljava/util/UUID;Lorg/spongepowered/asm/mixi
n/injection/callback/CallbackInfo;)V -> Parse]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethod
s(InjectionInfo.java:572) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnota
tion(InjectionInfo.java:288) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(Inj
ectionInfo.java:275) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(Inj
ectionInfo.java:267) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<i
nit>(CallbackInjectionInfo.java:46) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.GeneratedConstructorAccessor15.newInstance(Unkno
wn Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(De
legatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:
499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?
]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEn
try.create(InjectionInfo.java:140) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(Inje
ctionInfo.java:624) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInj
ections(MixinTargetContext.java:1247) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepa
reInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply
Mixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply
(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixin
s(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(Mi
xinProcessor.java:569) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(Mi
xinProcessor.java:351) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformCla
ss(MixinTransformer.java:208) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformCla
ssBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.t
ransformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.ja
r:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassBy
teArray(KnotClassDelegate.java:162) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLo
ader.java:154) [fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:1106) [?:?]
        at net.minecraft.server.Main.method_29734(Main.java:180) [intermediary-s
erver.jar:?]
        at net.minecraft.server.Main$$Lambda$3786/0x000000003181b288.apply(Unkno
wn Source) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.jav
a:260) [intermediary-server.jar:?]
        at net.minecraft.server.Main.main(Main.java:179) [intermediary-server.ja
r:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAcce
ssorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMe
thodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGamePr
ovider.java:234) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-se
rver-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [
fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAcce
ssorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMe
thodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricS
erverLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricSe
rverLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricSer
verLauncher.java:56) [fabric-server-launch.jar:?]
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric se
rver environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricSer
verLauncher.java:58)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception
occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricSe
rverLauncher.java:116)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricSer
verLauncher.java:56)
Caused by: java.lang.RuntimeException: An exception occurred when launching the
server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricS
erverLauncher.java:70)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricSe
rverLauncher.java:114)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricS
erverLauncher.java:68)
        ... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetExcepti
on
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGamePr
ovider.java:236)
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGamePr
ovider.java:234)
        ... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerEr
ror: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(Mi
xinProcessor.java:363)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformCla
ss(MixinTransformer.java:208)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformCla
ssBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.t
ransformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassBy
teArray(KnotClassDelegate.java:162)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLo
ader.java:154)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1106)
        at net.minecraft.server.Main.method_29734(Main.java:180)
        at net.minecraft.server.Main$$Lambda$3786/0x000000003181b288.apply(Unkno
wn Source)
        at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.jav
a:260)
        at net.minecraft.server.Main.main(Main.java:179)
        ... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [bukkit
fabric.mixins.json:network.MixinPlayerManager_ChatEvent] from phase [DEFAULT] in
 config [bukkitfabric.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinErr
or(MixinProcessor.java:642)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApp
lyError(MixinProcessor.java:594)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(Mi
xinProcessor.java:356)
        ... 24 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionExce
ption: Critical injection failure: @Inject annotation on cardboard_doChatEvent_P
LRMGR could not find any targets matching 'broadcast' in net.minecraft.class_332
4. Using refmap CardboardMod-refmap.json [PREINJECT Applicator Phase -> bukkitfa
bric.mixins.json:network.MixinPlayerManager_ChatEvent -> Prepare Injections ->
-> handler$zcp000$cardboard_doChatEvent_PLRMGR(Lnet/minecraft/class_2561;Ljava/u
til/function/Function;Lnet/minecraft/class_2556;Ljava/util/UUID;Lorg/spongepower
ed/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethod
s(InjectionInfo.java:572)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnota
tion(InjectionInfo.java:288)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(Inj
ectionInfo.java:275)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(Inj
ectionInfo.java:267)
        at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<i
nit>(CallbackInjectionInfo.java:46)
        at jdk.internal.reflect.GeneratedConstructorAccessor15.newInstance(Unkno
wn Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newI
nstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constru
ctor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:
480)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEn
try.create(InjectionInfo.java:140)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(Inje
ctionInfo.java:624)
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInj
ections(MixinTargetContext.java:1247)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepa
reInjections(MixinApplicatorStandard.java:1033)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply
Mixin(MixinApplicatorStandard.java:388)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply
(MixinApplicatorStandard.java:320)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixin
s(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(Mi
xinProcessor.java:569)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(Mi
xinProcessor.java:351)
        ... 24 more

```

**Comment by Anhelm** [comment]
Console text for the latest versions of the mod.

```

D:\Project Anhelm\albion>java -jar fabric-server-launch.jar
[15:59:08] [main/INFO]: Loading for game Minecraft 1.16.5
[15:59:08] [main/INFO]: [FabricLoader] Loading 54 mods:
        - architectury@1.22.32
        - cardboard@165
        - com_github_isaiahpatton_specialsource@master-SNAPSHOT
        - fabric@0.40.0+1.16
        - fabric-api-base@0.3.0+f74f7c7d7d
        - fabric-api-lookup-api-v1@1.3.0+f74f7c7d7d
        - fabric-biome-api-v1@3.1.11+f74f7c7d7d
        - fabric-blockrenderlayer-v1@1.1.5+ca58154a7d
        - fabric-command-api-v1@1.1.2+f74f7c7d7d
        - fabric-commands-v0@0.2.2+ca58154a7d
        - fabric-containers-v0@0.1.11+9354966b7d
        - fabric-content-registries-v0@0.2.4+f74f7c7d7d
        - fabric-crash-report-info-v1@0.1.3+ca58154a7d
        - fabric-dimensions-v1@2.0.6+f74f7c7d7d
        - fabric-entity-events-v1@1.2.3+77df1b337d
        - fabric-events-interaction-v0@0.4.4+35ff49a47d
        - fabric-events-lifecycle-v0@0.2.1+ca58154a7d
        - fabric-game-rule-api-v1@1.0.6+f74f7c7d7d
        - fabric-item-api-v1@1.2.1+ca58154a7d
        - fabric-item-groups-v0@0.2.7+2868a2287d
        - fabric-key-binding-api-v1@1.0.4+f74f7c7d7d
        - fabric-keybindings-v0@0.2.1+ca58154a7d
        - fabric-lifecycle-events-v1@1.2.1+ca58154a7d
        - fabric-loot-tables-v1@1.0.2+ca58154a7d
        - fabric-mining-levels-v0@0.1.3+ca58154a7d
        - fabric-models-v0@0.3.0+f74f7c7d7d
        - fabric-networking-api-v1@1.0.4+f74f7c7d7d
        - fabric-networking-blockentity-v0@0.2.8+ca58154a7d
        - fabric-networking-v0@0.3.2+ca58154a7d
        - fabric-object-builder-api-v1@1.9.5+f74f7c7d7d
        - fabric-object-builders-v0@0.7.2+ca58154a7d
        - fabric-particles-v1@0.2.4+ca58154a7d
        - fabric-registry-sync-v0@0.7.4+ca58154a7d
        - fabric-renderer-api-v1@0.4.4+f74f7c7d7d
        - fabric-renderer-indigo@0.4.4+ca58154a7d
        - fabric-renderer-registries-v1@2.3.0+f74f7c7d7d
        - fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d
        - fabric-rendering-fluids-v1@0.1.13+ca58154a7d
        - fabric-rendering-v0@1.1.2+ca58154a7d
        - fabric-rendering-v1@1.6.0+2868a2287d
        - fabric-resource-loader-v0@0.4.7+f74f7c7d7d
        - fabric-screen-api-v1@1.0.0+c045166c7d
        - fabric-screen-handler-api-v1@1.1.5+f74f7c7d7d
        - fabric-structure-api-v1@1.1.11+ca0ef93d7d
        - fabric-tag-extensions-v0@1.1.1+ca58154a7d
        - fabric-textures-v0@1.0.6+ca58154a7d
        - fabric-tool-attribute-api-v1@1.2.7+f74f7c7d7d
        - fabric-transfer-api-v1@1.3.0+35ff49a47d
        - fabricloader@0.11.6
        - java@16
        - kubejs@1605.3.15-build.106
        - minecraft@1.16.5
        - org_yaml_snakeyaml@1.27
        - rhino@1605.1.3-build.52
[15:59:08] [main/WARN]: Mod `com_github_isaiahpatton_specialsource` (master-SNAP
SHOT) does not respect SemVer - comparison support is limited.
[15:59:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:
/D:/Project%20Anhelm/albion/fabric-server-launch.jar Service=Knot/Fabric Env=SER
VER
[15:59:08] [main/INFO]: Compatibility level set to JAVA_16
[15:59:09] [main/INFO]: Loading Libraries...
[15:59:09] [main/WARN]: Reference map 'rhino-fabric-refmap.json' for rhino.mixin
s.json could not be read. If this is a development environment you can ignore th
is message
[15:59:09] [main/INFO]: Architectury Mod detected! Disabling async chat from Net
workHandler.
[15:59:09] [main/INFO]: Architectury Mod detected! Using alternative async chat
from PlayerManager
[15:59:09] [main/WARN]: Error loading class: net/minecraft/class_746 (java.lang.
ClassNotFoundException: net/minecraft/class_746)
[15:59:09] [main/WARN]: @Mixin target net.minecraft.class_746 was not found arch
itectury.mixins.json:PlayerAttackInvoker
[15:59:09] [main/WARN]: Error loading class: net/minecraft/class_745 (java.lang.
ClassNotFoundException: net/minecraft/class_745)
[15:59:09] [main/WARN]: @Mixin target net.minecraft.class_745 was not found arch
itectury.mixins.json:PlayerAttackInvoker
[15:59:15] [main/INFO]: Looking for KubeJS plugins...
[15:59:15] [main/INFO]: Found kubejs plugin
[15:59:15] [main/INFO]: Found rhino plugin
[15:59:15] [main/INFO]: Done in 0 s
[15:59:15] [main/INFO]: Loaded common.properties
[15:59:16] [main/INFO]:
[15:59:16] [main/INFO]: Cardboard Mod - CardboardPowered.org
[15:59:16] [main/INFO]:
[15:59:16] [main/INFO]: Reflection working: true
[15:59:17] [main/INFO]: Cardboard mod Loaded.
[15:59:17] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to err
ors, provided by 'kubejs'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke
0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke
(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start
(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar
:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAcce
ssorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMe
thodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGamePr
ovider.java:234) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-se
rver-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [
fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAcce
ssorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMe
thodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricS
erverLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricSe
rverLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricSer
verLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Wrapp
er for class java.lang.String already exists!
        at dev.latvian.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java
:33) ~[kubejs-fabric-1605.3.15-build.106%20(1).jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer$$Lamb
da$2302/0x00000000308fa0e8.accept(Unknown Source) ~[?:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke
0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more
Caused by: java.lang.IllegalArgumentException: Wrapper for class java.lang.Strin
g already exists!
        at dev.latvian.mods.rhino.util.wrap.TypeWrappers.register(TypeWrappers.j
ava:33) ~[rhino-fabric-1605.1.3-build.52%20(1).jar:?]
        at dev.latvian.mods.rhino.util.wrap.TypeWrappers.register(TypeWrappers.j
ava:61) ~[rhino-fabric-1605.1.3-build.52%20(1).jar:?]
        at dev.latvian.kubejs.BuiltinKubeJSPlugin.addTypeWrappers(BuiltinKubeJSP
lugin.java:255) ~[kubejs-fabric-1605.3.15-build.106%20(1).jar:?]
        at dev.latvian.kubejs.script.ScriptManager.lambda$load$3(ScriptManager.j
ava:105) ~[kubejs-fabric-1605.3.15-build.106%20(1).jar:?]
        at dev.latvian.kubejs.script.ScriptManager$$Lambda$2330/0x000000003170aa
40.accept(Unknown Source) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.latvian.kubejs.util.KubeJSPlugins.forEachPlugin(KubeJSPlugins.jav
a:108) ~[kubejs-fabric-1605.3.15-build.106%20(1).jar:?]
        at dev.latvian.kubejs.script.ScriptManager.load(ScriptManager.java:105)
~[kubejs-fabric-1605.3.15-build.106%20(1).jar:?]
        at dev.latvian.kubejs.KubeJS.<init>(KubeJS.java:124) ~[kubejs-fabric-160
5.3.15-build.106%20(1).jar:?]
        at dev.latvian.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java
:23) ~[kubejs-fabric-1605.3.15-build.106%20(1).jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer$$Lamb
da$2302/0x00000000308fa0e8.accept(Unknown Source) ~[?:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke
0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more

```
