### ISSUE TITLE
Llama with chest = crash. CardboardInventoryView.getTopInventory()" is null

### ISSUE THREAD

**Issue by TwoPointInfinity** [CardboardPowered/cardboard#325]
Tame a llama.
Put chest on llama
Server Crash
```
Error executing task on Server
java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.inventory.CraftInventory.getInventory()" because the return value of "org.cardboardpowered.impl.inventory.CardboardInventoryView.getTopInventory()" is null
	at net.minecraft.class_1703.transferTo(class_1703.java:915) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.handler$zdl000$doBukkit_InventoryCloseEvent(class_3244.java:2368) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12054(class_3244.java:1383) ~[server-intermediary.jar:?]
	at net.minecraft.class_2815.method_12198(class_2815.java:15) ~[server-intermediary.jar:?]
	at net.minecraft.class_2815.method_11054(class_2815.java:6) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600$$Lambda$6936/0x00000000c3dcdfe0.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) [server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) [server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zhf000$modifiedRunLoop(MinecraftServer.java:4365) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5549/0x00000000bf87bf68.run(Unknown Source) [server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:884) [?:?]
[21:31:13] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.inventory.CraftInventory.getInventory()" because the return value of "org.cardboardpowered.impl.inventory.CardboardInventoryView.getTopInventory()" is null
	at net.minecraft.class_1703.transferTo(class_1703.java:915) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.handler$zca000$cardboard_doInventoryCloseEvent(class_3222.java:2130) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_7346(class_3222.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_7291(class_3222.java:1053) ~[server-intermediary.jar:?]
	at net.minecraft.class_1496.method_6722(class_1496.java:428) ~[server-intermediary.jar:?]
	at net.minecraft.class_1492.method_5992(class_1492.java:169) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.method_5688(class_1308.java:1130) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_7287(class_1657.java:1059) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244$1$$Lambda$7731/0x00000000c2bd9f20.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3244$1.method_33897(class_3244.java:1318) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244$1.method_34219(class_3244.java:1329) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java:1315) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600$$Lambda$6936/0x00000000c3dcdfe0.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) [server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) [server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:741) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zhf000$modifiedRunLoop(MinecraftServer.java:4365) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5549/0x00000000bf87bf68.run(Unknown Source) [server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:884) [?:?]
[21:31:14] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:883) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zhf000$modifiedRunLoop(MinecraftServer.java:4356) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5549/0x00000000bf87bf68.run(Unknown Source) [server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:884) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.inventory.CraftInventory.getInventory()" because the return value of "org.cardboardpowered.impl.inventory.CardboardInventoryView.getTopInventory()" is null
	at net.minecraft.class_1703.transferTo(class_1703.java:915) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.handler$zca000$cardboard_doInventoryCloseEvent(class_3222.java:2130) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_7346(class_3222.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_5773(class_3222.java:445) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:699) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218$$Lambda$6387/0x00000000c228f808.accept(Unknown Source) ~[?:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:487) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:360) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218$$Lambda$6362/0x00000000c2389340.accept(Unknown Source) ~[?:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:328) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.redirect$zof000$fixUpdateSuppressionCrashTick(MinecraftServer.java:5250) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
	... 7 more
```

**Comment by TwoPointInfinity** [comment]
When the server is restarted, llamas and alike are deleted from the world.
