### ISSUE TITLE
SpecialSource ASM VerifyError crash when loading plugin

### ISSUE THREAD

**Issue by Merith-TK** [CardboardPowered/cardboard#52]
https://mclo.gs/RIOZzm4 Server Logs

Crash Report
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 11/5/20 1:01 AM
Description: Exception in server tick loop

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/md_5/specialsource/Jar.getNode(Ljava/lang/String;)Lorg/objectweb/asm/tree/ClassNode; @36: invokevirtual
  Reason:
    Type 'org/objectweb/asm/tree/ClassNode' (current frame, stack[1]) is not assignable to 'org/objectweb/asm/ClassVisitor'
  Current Frame:
    bci: @36
    flags: { }
    locals: { 'net/md_5/specialsource/Jar', 'java/lang/String', 'java/io/InputStream', null, 'org/objectweb/asm/ClassReader', 'org/objectweb/asm/tree/ClassNode' }
    stack: { 'org/objectweb/asm/ClassReader', 'org/objectweb/asm/tree/ClassNode', integer }
  Bytecode:
    0x0000000: 2a2b b600 5f4d 014e 2cc6 0043 bb00 6159
    0x0000010: 2cb7 0064 3a04 bb00 6659 b700 673a 0519
    0x0000020: 0419 0503 b600 6b19 053a 062c c600 1d2d
    0x0000030: c600 152c b600 6ea7 0012 3a07 2d19 07b6
    0x0000040: 0074 a700 072c b600 6e19 06b0 2cc6 004b
    0x0000050: 2dc6 0015 2cb6 006e a700 403a 042d 1904
    0x0000060: b600 74a7 0035 2cb6 006e a700 2e3a 0419
    0x0000070: 044e 1904 bf3a 082c c600 1d2d c600 152c
    0x0000080: b600 6ea7 0012 3a09 2d19 09b6 0074 a700
    0x0000090: 072c b600 6e19 08bf a700 0e4d bb00 7659
    0x00000a0: 2b2c b700 79bf 01b0                    
  Exception Handler Table:
    bci [51, 55] => handler: 58
    bci [84, 88] => handler: 91
    bci [8, 43] => handler: 109
    bci [8, 43] => handler: 117
    bci [127, 131] => handler: 134
    bci [109, 119] => handler: 117
    bci [0, 73] => handler: 155
    bci [76, 152] => handler: 155
  Stackmap Table:
    full_frame(@58,{Object[#2],Object[#112],Object[#82],Object[#93],Object[#97],Object[#102],Object[#102]},{Object[#93]})
    same_frame(@69)
    same_frame(@73)
    chop_frame(@76,3)
    same_locals_1_stack_item_frame(@91,Object[#93])
    same_frame(@102)
    same_locals_1_stack_item_frame(@109,Object[#93])
    same_locals_1_stack_item_frame(@117,Object[#93])
    full_frame(@134,{Object[#2],Object[#112],Object[#82],Object[#93],Top,Top,Top,Top,Object[#93]},{Object[#93]})
    same_frame(@145)
    same_frame(@149)
    full_frame(@152,{Object[#2],Object[#112]},{})
    same_locals_1_stack_item_frame(@155,Object[#74])
    same_frame(@166)

	at net.md_5.specialsource.SpecialSource.main(SpecialSource.java:289)
	at com.javazilla.bukkitfabric.nms.Remapper.runSpecialSource(Remapper.java:138)
	at com.javazilla.bukkitfabric.nms.Remapper.remap(Remapper.java:89)
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:347)
	at net.minecraft.class_3176.handler$zzh000$init(class_3176.java:708)
	at net.minecraft.class_3176.method_3823(class_3176.java:150)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (amd64) version 5.4.73-1-lts
	Java Version: 1.8.0_212, IcedTea
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), IcedTea
	Memory: 3708687968 bytes (3536 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 2
	JVM Flags: 3 total; -XX:+UseG1GC -Xms4G -Xmx4G
	Fabric Mods: 
		bukkitfabric: Bukkit for Fabric 1.16.3
		fabric: Fabric API 0.25.1+build.416-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d3a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b3a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce993a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f3a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf3a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c593a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b4623793a
		fabricloader: Fabric Loader 0.10.6+build.214
		geyser-fabric: Geyser-Fabric 1.0-SNAPSHOT
		lithium: Lithium 0.5.6
		minecraft: Minecraft 1.16.3
		phosphor: Phosphor 0.6.0+build.7
	Player Count: 0 / 20; []
	Data Packs: vanilla, fabric/fabric-tool-attribute-api-v1
	Is Modded: Definitely; Server brand changed to 'Fabric,Bukkit'
	Type: Dedicated Server (map_server.txt)
```

**Comment by IsaiahPatton** [comment]
Should be fixed now
