### ISSUE TITLE
Crash with plugin.

### ISSUE THREAD

**Issue by Mario0051** [CardboardPowered/cardboard#75]
I tried running this mod (1.17 fork) with the plugin called "OldCombatMechanics" and the crash is as follows (the Minecraft window stays open oddly enough):
```
[20:15:12] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.CraftServer.getGenerator(String)" because "org.bukkit.craftbukkit.CraftServer.INSTANCE" is null
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:1963) ~[intermediary-minecraft-20w46a-client.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:67) ~[intermediary-minecraft-20w46a-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[intermediary-minecraft-20w46a-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-20w46a-client.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[20:15:12] [Server thread/ERROR]: This crash report has been saved to: C:\Users\*****\Downloads\MultiMC\instances\20w46a\.minecraft\crash-reports\crash-2020-11-15_20.15.12-server.txt
[20:15:12] [Server thread/INFO]: Stopping server
[20:15:12] [Server thread/INFO]: Saving players
[20:15:12] [Server thread/INFO]: Saving worlds
[20:15:12] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "?" is null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:571) ~[intermediary-minecraft-20w46a-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:598) ~[intermediary-minecraft-20w46a-client.jar:?]
	at net.minecraft.class_1132.method_3782(class_1132.java:203) ~[intermediary-minecraft-20w46a-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:706) ~[intermediary-minecraft-20w46a-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-20w46a-client.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by IsaiahPatton** [comment]
This should be fixed now.
