### ISSUE TITLE
Worldguard - Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by L0rdLogan** [CardboardPowered/cardboard#78]
B4F build 128

Re-create - set /rg flag __global__ build deny - this disallows non server ops from building

Issue: Can place, but not break blocks
Expectation: Being unable to break and place blocks as a non OP

[08:44:20] [Server thread/FATAL]: Could not pass event PlayerInteractEvent to WorldGuard v7.0.4+f7ff984
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Bukkit4Fabric-1.16.4.jar:?]
        at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:227) ~[Bukkit4Fabric-1.16.4.jar:?]
        at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:195) ~[Bukkit4Fabric-1.16.4.jar:?]
        at net.minecraft.class_3225.handler$zhn000$processBlockBreakingActionBF(class_3225.java:612) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:1008) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:40) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.isBlockModifiedOnClick(EventAbstractionListener.java:1212) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteract(EventAbstractionListener.java:491) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[Bukkit4Fabric-1.16.4.jar:?]
        ... 24 more

Video demonstration: https://youtu.be/_UWv3Dq8L_0

**Comment by L0rdLogan** [comment]
Build #131 has the same error but seems even more broken - I now don't get any error messages shows to the player - https://youtu.be/AA7r8d5BGII

**Comment by IsaiahPatton** [comment]
Should be fixed now
