### ISSUE TITLE
WorldEdit - unable to replace blocks #build 130

### ISSUE THREAD

**Issue by L0rdLogan** [CardboardPowered/cardboard#87]
Worldedit version: worldedit-bukkit-7.2.0-dist

Edit: I am sorry to open a second issue, but the notes for build #130 claim it is fixed? If I misinterpreted "Fix LuckPerms and WorldEdit not working" please close this and use the previous issue raised 

[08:00:36] [Server thread/INFO]: L0rdLogan issued server command: /time set day
[08:00:43] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: net.minecraft.class_1723 cannot be cast to net.minecraft.class_3908
        at org.cardboardpowered.impl.entity.PlayerImpl.updateInventory(PlayerImpl.java:1109) ~[Bukkit4Fabric-1.16.4.jar:?]
        at net.minecraft.class_3225.handler$zhn001$interactBlock(class_3225.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[08:00:43] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: net.minecraft.class_1723 cannot be cast to net.minecraft.class_3908
        at org.cardboardpowered.impl.entity.PlayerImpl.updateInventory(PlayerImpl.java:1109) ~[Bukkit4Fabric-1.16.4.jar:?]
        at net.minecraft.class_3244.handler$zjl000$onPlayerInteractItemBF(class_3244.java:2216) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12065(class_3244.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_2886.method_12550(class_2886.java:31) ~[intermediary-server.jar:?]
        at net.minecraft.class_2886.method_11054(class_2886.java:9) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[08:00:43] [Server thread/FATAL]: Could not pass event PlayerInteractEvent to WorldGuard v7.0.4+f7ff984
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Bukkit4Fabric-1.16.4.jar:?]
        at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:227) ~[Bukkit4Fabric-1.16.4.jar:?]
        at net.minecraft.class_3225.handler$zhn001$interactBlock(class_3225.java:799) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ExceptionInInitializerError
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.isBlockModifiedOnClick(EventAbstractionListener.java:1212) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteract(EventAbstractionListener.java:491) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[Bukkit4Fabric-1.16.4.jar:?]
        ... 23 more
Caused by: java.lang.NullPointerException
        at java.util.EnumMap.typeCheck(Unknown Source) ~[?:1.8.0_251]
        at java.util.EnumMap.put(Unknown Source) ~[?:1.8.0_251]
        at java.util.EnumMap.put(Unknown Source) ~[?:1.8.0_251]
        at com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:757) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.isBlockModifiedOnClick(EventAbstractionListener.java:1212) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteract(EventAbstractionListener.java:491) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[Bukkit4Fabric-1.16.4.jar:?]
        ... 23 more
[08:00:43] [Server thread/FATAL]: Could not pass event PlayerInteractEvent to WorldGuard v7.0.4+f7ff984
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Bukkit4Fabric-1.16.4.jar:?]
        at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:227) ~[Bukkit4Fabric-1.16.4.jar:?]
        at net.minecraft.class_3225.handler$zhn001$interactBlock(class_3225.java:799) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.handleBlockRightClick(WorldGuardPlayerListener.java:266) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerInteract(WorldGuardPlayerListener.java:227) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[Bukkit4Fabric-1.16.4.jar:?]
        ... 23 more
[08:00:44] [Server thread/INFO]: [STDOUT]: DROP STACK TEST
[08:00:49] [Server thread/INFO]: [STDOUT]: DROP STACK TEST
[08:01:03] [Server thread/INFO]: [STDOUT]: DROP STACK TEST
[08:01:03] [Server thread/INFO]: [STDOUT]: DROP STACK TEST
[08:01:08] [Server thread/INFO]: L0rdLogan issued server command: //replace dirt cobblestone
[08:01:08] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.ExceptionInInitializerError: null
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:268) ~[?:?]
        at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[?:?]
        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1009) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:249) ~[?:?]
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_251]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:248) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
        at java.util.Optional.flatMap(Unknown Source) ~[?:1.8.0_251]
        at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_251]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_251]
        at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
        at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
        at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
        at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:647) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_replace(RegionCommandsRegistration.java:450) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:494) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:375) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:842) ~[Bukkit4Fabric-1.16.4.jar:?]
        at net.minecraft.class_3244.handler$zjl000$executeCommand(class_3244.java:1777) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_14370(class_3244.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12048(class_3244.java:1872) ~[intermediary-server.jar:?]
        at net.minecraft.class_2797.method_12115(class_2797.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2797.method_11054(class_2797.java:9) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[server.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitAdapter.asBlockType(BukkitAdapter.java:418) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_251]
        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_251]
        at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getFromBukkitTag(BukkitBlockCategoryRegistry.java:37) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getCategorisedByName(BukkitBlockCategoryRegistry.java:48) ~[?:?]
        at com.sk89q.worldedit.world.registry.CategoryRegistry.getAll(CategoryRegistry.java:41) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockCategory.load(BlockCategory.java:46) ~[?:?]
        at com.sk89q.worldedit.registry.Category.getAll(Category.java:40) ~[?:?]
        at com.sk89q.worldedit.extent.reorder.MultiStageReorder.<clinit>(MultiStageReorder.java:58) ~[?:?]
        ... 58 more
[08:01:13] [Server thread/INFO]: [STDOUT]: DROP STACK TEST
[08:01:14] [Server thread/INFO]: [STDOUT]: DROP STACK TEST
[08:01:20] [Server thread/INFO]: L0rdLogan lost connection: Disconnected
[08:01:20] [Server thread/INFO]: L0rdLogan left the game
[08:01:20] [Server thread/INFO]: [STDOUT]: 238 path depth entries saved to world nbt
[08:01:28] [Server thread/INFO]: [STDOUT]: DROP STACK TEST

**Comment by IsaiahPatton** [comment]
try build 131

**Comment by IsaiahPatton** [comment]
should be fixed
